
<table class="ss autocenter" style="width:400px">
 <tbody>
  <tr class="ss_header">
   <th>Species</th>
   <th class="right">Data size (Gb)</th>
  </tr>
  <tr class="bg1">
   <td>Ailuropoda melanoleuca</td>
   <td class="right">7.2</td>
  </tr>
  <tr class="bg2">
   <td>Anolis carolinensis</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg1">
   <td>Bos taurus</td>
   <td class="right">21.1</td>
  </tr>
  <tr class="bg2">
   <td>Caenorhabditis elegans</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Callithrix jacchus</td>
   <td class="right">8.4</td>
  </tr>
  <tr class="bg2">
   <td>Canis familiaris</td>
   <td class="right">13.6</td>
  </tr>
  <tr class="bg1">
   <td>Cavia porcellus</td>
   <td class="right">7.3</td>
  </tr>
  <tr class="bg2">
   <td>Choloepus hoffmanni</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg1">
   <td>Ciona intestinalis</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Ciona savignyi</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Danio rerio</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Dasypus novemcinctus</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg1">
   <td>Dipodomys ordii</td>
   <td class="right">10.4</td>
  </tr>
  <tr class="bg2">
   <td>Drosophila melanogaster</td>
   <td class="right">9.9</td>
  </tr>
  <tr class="bg1">
   <td>Echinops telfairi</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg2">
   <td>Equus caballus</td>
   <td class="right">8.3</td>
  </tr>
  <tr class="bg1">
   <td>Erinaceus europaeus</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg2">
   <td>Felis catus</td>
   <td class="right">8.3</td>
  </tr>
  <tr class="bg1">
   <td>Gadus morhua</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg2">
   <td>Gallus gallus</td>
   <td class="right">7.0</td>
  </tr>
  <tr class="bg1">
   <td>Gasterosteus aculeatus</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg2">
   <td>Gorilla gorilla</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Ictidomys tridecemlineatus</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg2">
   <td>Latimeria chalumnae</td>
   <td class="right">8.8</td>
  </tr>
  <tr class="bg1">
   <td>Loxodonta africana</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg2">
   <td>Macaca mulatta</td>
   <td class="right">9.2</td>
  </tr>
  <tr class="bg1">
   <td>Macropus eugenii</td>
   <td class="right">6.0</td>
  </tr>
  <tr class="bg2">
   <td>Meleagris gallopavo</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Microcebus murinus</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg2">
   <td>Monodelphis domestica</td>
   <td class="right">11.5</td>
  </tr>
  <tr class="bg1">
   <td>Mus musculus</td>
   <td class="right">97.2</td>
  </tr>
  <tr class="bg2">
   <td>Mustela putorius</td>
   <td class="right">13.7</td>
  </tr>
  <tr class="bg1">
   <td>Myotis lucifugus</td>
   <td class="right">6.9</td>
  </tr>
  <tr class="bg2">
   <td>Nomascus leucogenys</td>
   <td class="right">8.3</td>
  </tr>
  <tr class="bg1">
   <td>Ochotona princeps</td>
   <td class="right">9.1</td>
  </tr>
  <tr class="bg2">
   <td>Oreochromis niloticus</td>
   <td class="right">11.8</td>
  </tr>
  <tr class="bg1">
   <td>Ornithorhynchus anatinus</td>
   <td class="right">8.6</td>
  </tr>
  <tr class="bg2">
   <td>Oryctolagus cuniculus</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Oryzias latipes</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Otolemur garnettii</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg1">
   <td>Pan troglodytes</td>
   <td class="right">12.4</td>
  </tr>
  <tr class="bg2">
   <td>Pelodiscus sinensis</td>
   <td class="right">8.4</td>
  </tr>
  <tr class="bg1">
   <td>Petromyzon marinus</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Pongo abelii</td>
   <td class="right">15.1</td>
  </tr>
  <tr class="bg1">
   <td>Procavia capensis</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg2">
   <td>Pteropus vampyrus</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg1">
   <td>Rattus norvegicus</td>
   <td class="right">18.6</td>
  </tr>
  <tr class="bg2">
   <td>Saccharomyces cerevisiae</td>
   <td class="right">0.5</td>
  </tr>
  <tr class="bg1">
   <td>Sarcophilus harrisii</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg2">
   <td>Sorex araneus</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg1">
   <td>Sus scrofa</td>
   <td class="right">10.6</td>
  </tr>
  <tr class="bg2">
   <td>Taeniopygia guttata</td>
   <td class="right">6.8</td>
  </tr>
  <tr class="bg1">
   <td>Takifugu rubripes</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg2">
   <td>Tarsius syrichta</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg1">
   <td>Tetraodon nigroviridis</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Tupaia belangeri</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg1">
   <td>Tursiops truncatus</td>
   <td class="right">6.3</td>
  </tr>
  <tr class="bg2">
   <td>Vicugna pacos</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Xenopus tropicalis</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Xiphophorus maculatus</td>
   <td class="right">10.9</td>
  </tr>
  <tr>
   <th>Sub-total</th>
   <th class="right">564.4</th>
  </tr>

  <tr>
   <th>Multi-species</th>
   <th></th>
  </tr>
  <tr class="bg1">
   <td>Ancestral</td>
   <td class="right">36.2</td>
  </tr>
  <tr class="bg2">
   <td>Compara</td>
   <td class="right">235.7</td>
  </tr>
  <tr class="bg1">
   <td>Mart</td>
   <td class="right">696.6</td>
  </tr>
  <tr class="bg2">
   <td>Ontology</td>
   <td class="right">0.1</td>
  </tr>
  <tr>
   <th>Total</th>
   <th class="right">1533.1</th>
  </tr>
 </tbody>
</table>
