
<table class="ss autocenter" style="width:50%;margin:0 25%" cellspacing="0">
 <tbody>
  <tr class="ss_header">
   <th class="bottom-border left-border">Species</th>
   <th class="bottom-border right-border">Data size (Gb)</th>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Aedes aegypti                   </td>
   <td class="right-border" style="text-align:right">5.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Anolis carolinensis             </td>
   <td class="right-border" style="text-align:right">7.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Anopheles gambiae               </td>
   <td class="right-border" style="text-align:right">2.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Bos taurus                      </td>
   <td class="right-border" style="text-align:right">10.3       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Caenorhabditis elegans          </td>
   <td class="right-border" style="text-align:right">2.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Canis familiaris                </td>
   <td class="right-border" style="text-align:right">10.2       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Cavia porcellus                 </td>
   <td class="right-border" style="text-align:right">7.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Choloepus hoffmanni             </td>
   <td class="right-border" style="text-align:right">4.2        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Ciona intestinalis              </td>
   <td class="right-border" style="text-align:right">2.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Ciona savignyi                  </td>
   <td class="right-border" style="text-align:right">2.7        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Danio rerio                     </td>
   <td class="right-border" style="text-align:right">8.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Dasypus novemcinctus            </td>
   <td class="right-border" style="text-align:right">5.6        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Dipodomys ordii                 </td>
   <td class="right-border" style="text-align:right">10.3       </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Drosophila melanogaster         </td>
   <td class="right-border" style="text-align:right">1.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Echinops telfairi               </td>
   <td class="right-border" style="text-align:right">5.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Equus caballus                  </td>
   <td class="right-border" style="text-align:right">7.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Erinaceus europaeus             </td>
   <td class="right-border" style="text-align:right">7.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Felis catus                     </td>
   <td class="right-border" style="text-align:right">6.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Gallus gallus                   </td>
   <td class="right-border" style="text-align:right">10.5       </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Gasterosteus aculeatus          </td>
   <td class="right-border" style="text-align:right">4.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Gorilla gorilla                 </td>
   <td class="right-border" style="text-align:right">7.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Homo sapiens                    </td>
   <td class="right-border" style="text-align:right">66.3       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Loxodonta africana              </td>
   <td class="right-border" style="text-align:right">5.6        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Macaca mulatta                  </td>
   <td class="right-border" style="text-align:right">6.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Microcebus murinus              </td>
   <td class="right-border" style="text-align:right">5.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Monodelphis domestica           </td>
   <td class="right-border" style="text-align:right">9.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Mus musculus                    </td>
   <td class="right-border" style="text-align:right">30.7       </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Myotis lucifugus                </td>
   <td class="right-border" style="text-align:right">5.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Ochotona princeps               </td>
   <td class="right-border" style="text-align:right">9.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Ornithorhynchus anatinus        </td>
   <td class="right-border" style="text-align:right">7.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Oryctolagus cuniculus           </td>
   <td class="right-border" style="text-align:right">6.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Oryzias latipes                 </td>
   <td class="right-border" style="text-align:right">4.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Otolemur garnettii              </td>
   <td class="right-border" style="text-align:right">5.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Pan troglodytes                 </td>
   <td class="right-border" style="text-align:right">9.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Pongo pygmaeus                  </td>
   <td class="right-border" style="text-align:right">8.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Procavia capensis               </td>
   <td class="right-border" style="text-align:right">5.7        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Pteropus vampyrus               </td>
   <td class="right-border" style="text-align:right">5.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Rattus norvegicus               </td>
   <td class="right-border" style="text-align:right">11.7       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Saccharomyces cerevisiae        </td>
   <td class="right-border" style="text-align:right">0.2        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Sorex araneus                   </td>
   <td class="right-border" style="text-align:right">5.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Spermophilus tridecemlineatus   </td>
   <td class="right-border" style="text-align:right">5.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Taeniopygia guttata             </td>
   <td class="right-border" style="text-align:right">5.6        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Takifugu rubripes               </td>
   <td class="right-border" style="text-align:right">4.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Tarsius syrichta                </td>
   <td class="right-border" style="text-align:right">5.7        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Tetraodon nigroviridis          </td>
   <td class="right-border" style="text-align:right">4.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Tupaia belangeri                </td>
   <td class="right-border" style="text-align:right">6.5        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Tursiops truncatus              </td>
   <td class="right-border" style="text-align:right">6.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Vicugna pacos                   </td>
   <td class="right-border" style="text-align:right">4.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Xenopus tropicalis              </td>
   <td class="right-border" style="text-align:right">6.5        </td>
  </tr>
  <tr>
   <th class="left-border">Sub-total</th>
   <th class="right-border" style="text-align:right">388.3      </th>
  </tr>

  <tr>
   <th class="left-border">Multi-species</th>
   <th class="right-border">&nbsp;</th>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Compara                         </td>
   <td class="right-border" style="text-align:right">166.3      </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Go                              </td>
   <td class="right-border" style="text-align:right">8.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Mart                            </td>
   <td class="right-border" style="text-align:right">177.7      </td>
  </tr>
  <tr>
   <th class="left-border">Total</th>
   <th class="right-border" style="text-align:right">741.3      </th>
  </tr>
 </tbody>
</table>
