#!/usr/local/bin/perl

use strict;

my $ENSEMBL_ROOT;

BEGIN {
  use FindBin qw($Bin);
  use File::Basename qw( dirname );
  $ENSEMBL_ROOT = dirname( $Bin );
  $ENSEMBL_ROOT =~ s/\/utils$//;
}

use lib "$ENSEMBL_ROOT/modules";

package indexDumper;

use constant INC_SPECIES => 0;

my $species = shift;

open O, ">input/$species/SNP.txt";

while(<STDIN>) {
  chomp;
  my( $X, $source, $ID, @IDS ) = split / /;
  my @IDS2 = map { my($X,$Y) = split /:/; $Y } @IDS;
  print O &snpLine( $species, $source, $ID, "$ID @IDS2", "@IDS" );   
}

sub snpLine {
  my ($species, $source, $snpid, $IDS, $desc ) =@_;
  return if $snpid eq '';
  $desc =~ s/^, //;
  return join "\t",
    (INC_SPECIES?"$species\t":"").qq(EnsEMBL SNP),
    $snpid,
    "/$species/snpview?snp=$snpid&source=$source",
    "$IDS",
    "SNP $snpid. Alternative IDs: $desc.\n";
}

