[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["src/python/tests"]
norecursedirs = ["data", "tmp*", "env", "docs", "apps", "basic_modules", "*.egg_info"]

[tool.coverage.run]
source = ["src/python/lib"]

[tool.mypy]
python_version = 3.7
mypy_path = "src/python/lib"
ignore_missing_imports = true