#!/usr/local/bin/perl

package alignsliceview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'alignsliceview',
  'objecttype' => 'Location',
);

if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'alignsliceview', 'context_menu' );
  }
  $webpage->factory->fix_session;
  $webpage->render();
}

1;
