#!/usr/local/bin/perl 
##############################################################################
#
#   Description:    Script to paginate and display disease data
#
#   Author:         jws
#                   Disease objects by Arek
#
#   History:        2000-09-29
#                   2000-10-20  jws: improved portability
#
##############################################################################
package diseaseview;

use strict;
use ExtURL;
use DiseaseHandler;
use EnsWeb;
use EnsEMBL::DB::Core;
use EnsEMBL::HTML::Page;
use CGI qw/:standard :form :netscape3/;

my $q = new CGI;
my $urls = ExtURL->new;
$| = 1 ;

####################
# Print page header
####################
if( defined( $ENV{'MOD_PERL'} ) ) {
    my $r = Apache->request();    
    print $q->header();
    $r->err_header_out('ensembl_headers_out'=>1);
    print ensembl_page_header(('initfocus'=>0, 'menus'=>0));
    print ensembl_search_table($q->param('disease')||"",'disease');
    print "<br>";
}

######################################################
# initialise the databases, or we may as well go home
######################################################
my $databases = &EnsEMBL::DB::Core::get_databases( 'core', 'disease' );
&ensembl_warning(
   "Ensembl database problem",
   "Sorry, the Ensembl database is currently unavailable.<br />".
   $databases->{'error'}
) if($databases->{'error'});

&ensembl_warning(
   "No disease data available",
   "There is no disease database currently available for this species.<br />"
   ,1
) unless($databases->{'disease'});

#########################
# Set up page parameters 
#########################
my $num_per_page=8;                     # number of data rows per webpage
my $row = $q->param('rw');              # number of first row on the page
$row = 0 unless ($row && $row >=0);
my $chr = $q->param('chr')||"1";        #what chromosome are we on?

my $script_name=qq(/$ENV{'ENSEMBL_SPECIES'}/$ENV{'ENSEMBL_SCRIPT'});

my $rowcount;                   # number of data rows in database

my $length  = $row+$num_per_page-1;
my $prev    = $row-$num_per_page;
$prev       = 0 if $prev < 0;

my $search_str = $q->param('disease');
my $omimid     = $q->param('omimid');
my @omimid_res;

#########################
# Get the number of rows
#########################
if ($search_str){
    $rowcount = $databases->{'disease'}->diseases_by_keyword_count($search_str);
} elsif ($chr eq "ALL"){
    $rowcount = $databases->{'disease'}->all_disease_count;
} elsif( $omimid ){
    @omimid_res = $databases->{'disease'}->disease_by_omim_id($omimid);
    if( ! scalar( @omimid_res ) ){
        ensembl_warning( "Disease not found", "No disease found with an OMIM id of $omimid" );
    }
    $rowcount=1;
} else {
    $rowcount=$databases->{'disease'}->diseases_on_chromosome_count( $chr );
}

#################
# Setup heading
#################
my $header_string;
if ($search_str){
    $header_string=qq(Search for "$search_str" ($rowcount OMIM diseases));
} else {
    $header_string="Chromosome: $chr ($rowcount OMIM diseases)";
}



############################
# Print chromosome selector
############################
print qq(
<table cellspacing="0" cellpadding="0" border="0" width="100%" class="background1">
    <tr>
        <td colspan="7" class="black"><img src="/gfx/blank.gif" width="1" height="1"></td>
    </tr>   
    <tr>
        <td colspan="7"><img src="/gfx/blank.gif" height="2"></td>
    </tr>
    <tr>
        <td>&nbsp;&nbsp;</td>
        <td><span class="h4">$header_string</span></td>
        <td class="smarial" align="right" nowrap>&nbsp;&nbsp;Display <b>all</b> OMIM diseases on Chr: </td>
        <td align="right" nowrap><form action="$script_name" method="GET" name="chromosome"><select name="chr" class="white"  onChange='javascript:location="$script_name?chr="+this.options[this.selectedIndex].value;'>
);

foreach ( @{EnsWeb::species_defs->ENSEMBL_CHROMOSOMES} ) {
    print qq( <option value="$_" ). ($_ eq $chr ? ' selected' : ''). qq(>$_</option>\n);
}

print qq(
    </select>
        </td>
        <td>
            <INPUT TYPE="image" VALUE="lookup" src="/gfx/lookup.gif" border="0">
        </td>
        <td></form></td>
        <td>&nbsp;&nbsp;</td>
      <tr>
        <td colspan="7"><img src="/gfx/blank.gif" height="2"></td>
      </tr>
    </table>
);


#######################
# Table heading
#######################
print qq(
<table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td colspan="11" class="black"><img src="/gfx/blank.gif" width="1" height="1"></td>
    </tr>
     <tr valign="center" class="background1">
      <th><img src="/gfx/blank.gif" width="5" height="22"></th>
      <th align="left" class="arial">&nbsp;&nbsp;Ensembl id</th>
      <th class="arial">&nbsp;</th>
      <th align="left" class="arial">HUGO synonyms</th>
      <th class="arial">&nbsp;</th>
      <th align="left" class="arial">OMIM id</th>
      <th class="arial">&nbsp;</th>
      <th align="center" class="arial">Chromosome</th>
      <th class="arial">&nbsp;</th>
      <th align="center" class="arial">Cytolocation</th>
      <th><img src="/gfx/blank.gif" width="5" height="22"></th>
    </tr>
    <tr>
        <td colspan="11" class="black"><img src="/gfx/blank.gif" width="1" height="1"></td>
    </tr>
);

##############################################
# pull out the required disease objects
##############################################
my @diseases;
if ($search_str){
    @diseases=$databases->{'disease'}->diseases_by_keyword($search_str,$row,$num_per_page);
} elsif( $omimid ){
    @diseases = @omimid_res;
} elsif ($chr eq "ALL"){
    @diseases=$databases->{'disease'}->all_diseases($row,$num_per_page);
} else {
    @diseases=$databases->{'disease'}->diseases_on_chromosome($chr,$row,$num_per_page);
}

my $spacer_cell=qq(<td><img border="0" alt="" src="/gfx/blank.gif" width="5" height="22"></td>\n);

foreach my $dis_obj (@diseases){
    print qq(
<tr class="background2">
  <td><img src="/gfx/blank.gif" width="5" height="22"></td>
  <td colspan="9"><b>@{[$dis_obj->name]}</b></td>
  <td><img src="/gfx/blank.gif" width="5" height="22"></td>
</tr>
);
    my %loc;

    foreach my $location($dis_obj->each_Location){
	#######################################################################
	# OK, this is a little stupid.  Each location for a disease currently
	# has identical omim_id, cyto_start, cyto_end and chr.  The only thing
	# that differs is the external_gene id.  So, we're going to group the
	# location by omim_id (in case there are ever more than one id for a 
	# single disease), and just overwrite the common data each time
	#######################################################################
        my $omim_id = $location->db_id;
	if ($loc{$omim_id}{'external_gene'}){
	    $loc{$omim_id}{'external_gene'} = $loc{$omim_id}{'external_gene'}.", ".$location->external_gene;
	}
	else {
	    $loc{$omim_id}{'external_gene'}	= $location->external_gene;
	}
	$loc{$omim_id}{'cyto_start'}	= $location->cyto_start;
	$loc{$omim_id}{'cyto_end'}	= $location->cyto_end;
	$loc{$omim_id}{'chr'}		= $location->chromosome;
	$loc{$omim_id}{'ensembl_gene'}	= $location->ensembl_gene if defined $location->ensembl_gene;
    }

    foreach my $location(keys %loc){
	my $cyto_start	= $loc{$location}{'cyto_start'};	
	my $cyto_end	= $loc{$location}{'cyto_end'};	
	my $chr		= $loc{$location}{'chr'};	
	my $ens_gene	= $loc{$location}{'ensembl_gene'};	
	my $external_id = $loc{$location}{'external_gene'};

        my $cyto_location   = $cyto_start;
        $cyto_location     .= " - $cyto_end" unless ($cyto_start eq $cyto_end);
        my $csome  = qq(<a href="/$ENV{'ENSEMBL_SPECIES'}/mapview?chr=$chr">$chr</a>);

        #######################
        # Configure hyperlinks
        #######################
	my $ensembl_id;
        if (defined $ens_gene){
            $ensembl_id = qq(<a href="/$ENV{'ENSEMBL_SPECIES'}/geneview?gene=).
                        $ens_gene->stable_id.qq(">).
                        $ens_gene->stable_id.qq(</a>);
        } else {
            $ensembl_id = "No ensembl prediction";
        }
        
        my $omim_id=qq(<a href=").$urls->get_url('OMIM',$location).qq(" target="new">$location</a>);
            
        print qq(
        <tr class="background1">    
          <td><img src="/gfx/blank.gif" width="5" height="22"></td>
          <td class="arial">&nbsp;&nbsp;$ensembl_id</td>
          <td class="arial">&nbsp;&nbsp;</td>
          <td class="arial">&nbsp;$external_id</td>
          <td class="arial">&nbsp;&nbsp;</td>
          <td class="arial">&nbsp;$omim_id</td>
          <td class="arial">&nbsp;&nbsp;</td>
          <td align="center" class="arial">&nbsp;$csome</td>
          <td class="arial">&nbsp;&nbsp;</td>
          <td align="center" class="arial">&nbsp;$cyto_location</td>
          <td><img src="/gfx/blank.gif" width="5" height="22"></td>
        </tr>       
        );
    }

}

$length++;  # to correct the off-by-one;
my $current_page    =   int(($row+1)/$num_per_page);
   $current_page++  if ($row+1) % $num_per_page;
my $num_pages       =   int($rowcount/$num_per_page);
   $num_pages++     if $rowcount % $num_per_page;

print qq(
    <tr>
        <td colspan="11" class="grey1"><img src="/gfx/blank.gif" width="1" height="1"></td>
    </tr>
</table>
<br>

<table align="center" border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr align="center">
        <td>
);

if ($rowcount && $num_pages!=1){
    my $esc_search_str=$q->escape($search_str);
    foreach my $i (1..$num_pages){
        my $page_top=($i-1)*$num_per_page;
        $page_top=0 if $i==1;
            
        if ($i==$current_page){
            print qq|<b>[ $i ]</b>\n|;
        } else {
            print qq|[ <a href="$script_name?rw=$page_top&chr=$chr&disease=$esc_search_str">$i</a> ]\n|;
        }
    }
}
            
print qq(
    </tr>
</table>
<br>
);
print ensembl_page_footer();

use Bio::EnsEMBL::Registry; Bio::EnsEMBL::Registry->disconnect_all();1;
