#!/usr/local/bin/perl

package glossaryview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

## we need to instantiate a WebPage object in order to pick up CGI parameters,
## even if we don't end up outputting anything to the browser
my $webpage = new EnsEMBL::Web::Document::WebPage(
    'use_proxy'    => 1,
    'renderer'     => 'Apache',
    'outputtype'   => 'HTML',
    'scriptname'   => 'glossaryview',
    'objecttype'   => 'Help',
);

if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
}
else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'glossaryview'); ## this call creates wizard
  }
  $webpage->action; 
}

1;
