#!/usr/local/bin/perl

package haplotag;
use strict;
use EnsWeb;
use EnsEMBL::HTML::Page;
use CGI qw/:standard :form :netscape3/;

my $q = new CGI;
my $r =Apache->request();

print header(),
      ensembl_page_header( 'initfocus'=>1 );
print qq(
<form method="post" action="tag_response" target="new">
  <table width="80%" border="0" cellpadding = "4" >
    <tr>
      <td colspan="2">
        <p class="query">SNP id's list</p>
        <p>
          <input type=text name="snp_id_list" size="60" class="form" value="id1 di2 id3 id4 id5 id6 id7 id8 id9 id10">
        </p>
      </td>
    </tr>
    <tr>
      <td>
        <p class="query">Family ID and frequency</p>
        <p>
          <textarea name="pop_info" cols="20" rows="7" class="form">
HAPP01 0.58182
HAPP02 0.21818
HAPP03 0.18182
HAPP04 0.01818
          </textarea>
        </p>
      </td>
      <td>
        <p class="query">This is the haplotype</p>
        <p>
          <textarea name="hap_block" cols="60" rows="7" class="form">
actgacacac
cctgacacac
agtccccccc
ccagaaanaa
          </textarea>
        </p>
      </td>
    </tr>
    <tr>
      <td colspan="2"> 
        <p class="query">Selected families</p>
        <p>
          <input type=text name="selected_fam" size="60" class="form" value="0 1 2 3">
        </p>
      </td>
    </tr>
    <tr>
      <td >
        <input type="submit" name="submit" 
          value="I'll see what I can do" class="query">
      </td>
      <td>
        <input type="reset" name="reset"
          value="I have changed my mind" class="query">
      </td>
    </tr>
  </table>
</form>
);#"

print ensembl_page_footer();

use Bio::EnsEMBL::Registry; Bio::EnsEMBL::Registry->disconnect_all();1;


