#!/usr/local/bin/perl

package karyoview;

# N.B. Needs the full version of the view script as it uses a
# custom context menu

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'use_proxy'  => 1,
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'karyoview',
  'objecttype' => 'Chromosome',
);
if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'karyoview', 'context_karyoview' );
  }
  $webpage->render();
}

1;
