#!/usr/local/bin/perl

package ldview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;
use EnsEMBL::Web::Proxy::Object;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'scriptname' => 'ldview',
  'objecttype' => 'Location',
);


if ($webpage->has_a_problem ) {
  $webpage->render_error_page;
}
else {
  $webpage->{'show_fatal_only'} = 1;
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'ldview', 'context_menu' );
    foreach (qw(snp gene)) {
      if( @{$object->__data->{$_}||[]} ) {
	$webpage->configure( $object->__data->{$_}->[0], 'context_menu' );
      }
    }
    $webpage->factory->fix_session;
  }
  $webpage->{factory}->clear_problems();
  $webpage->render;
}

1;
