#!/usr/local/bin/perl

package martlink;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;
                                                                                
my $webpage= new EnsEMBL::Web::Document::WebPage(
  'scriptname' => 'martlink',
  'objecttype' => 'MartLink',
);

if( $webpage->has_problem_type( 'redirect') ) {
  #print "Content-type: text/plain\n\n",$webpage->problem->[0]->name;
  #exit;
  $webpage->redirect( $webpage->problem->[0]->name );
} else {
  $webpage->render_error_page;
}

1;
