#!/usr/local/bin/perl

package newsdbview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'use_proxy'  => 1,
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'newsdbview',
  'objecttype' => 'News',
);
if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  my $object = $webpage->dataObjects->[0];
  if ($object->param('submit') =~ /Save/) {
    # do database save
    $object->save_to_db;
    # return to first page
    my $URL = '/'.$object->species.'/newsdbview?action=saved';
    $webpage->redirect( $URL );
  }
  else {
    foreach my $object( @{$webpage->dataObjects} ) {
        $webpage->configure( $object, 'newsdbview', 'editor_menu');
    }
    $webpage->render();
  }
}


1;
