#!/usr/local/bin/perl

package newsview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'use_proxy'  => 1,
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'newsview',
  'objecttype' => 'News',
);
if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  my $object = $webpage->dataObjects->[0];
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'newsview', 'context_menu');
  }
  $webpage->render();
}


1;
