#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Tools::PluginLocator;
use EnsEMBL::Web::Interface::ZMenuCollection;
use EnsEMBL::Web::RegObj;

warn("AJAX: Populating ZMENU"); 

my $T = new CGI;
my $type = $T->param('type');
my $ident = $T->param('ident');

my $species_defs = $ENSEMBL_WEB_REGISTRY->species_defs;

my $locator = EnsEMBL::Web::Tools::PluginLocator->new((
                               locations => [ 
                                             'EnsEMBL::Web',
                                             @{ $species_defs->ENSEMBL_PLUGIN_ROOTS } 
                                            ],
                               suffix    => "Interface::ZMenu::$type",
                               method    => "populate"
                               ));

warn "SPECIES: " . @{ $locator->locations };

print "Content-type: text/plain\n\n";

if ($locator->include) {
  my $json = "";
  my $collection = EnsEMBL::Web::Interface::ZMenuCollection->new();
  my $zmenu;
  foreach my $class (@{ $locator->children }) {
    my $type_class = "EnsEMBL::Web::Interface::ZMenu::$type";
    $zmenu = $class->new(( type => $type, ident => $ident ));
    $zmenu->populate((species_defs => $species_defs));
    $collection->process($zmenu->add_list, $zmenu->remove_list);
  }
  $json = $collection->json($zmenu, ( escape => "no" ));
  warn "JSON: " . $json;
  print $json; 

} else {
  print "{ menu: { error: 'Problem!' } }";
}

1;
