#! /usr/local/bin/perl

package populate_info_fragment;

use strict;
use warnings;
no warnings "uninitialized";

use CGI;

use EnsEMBL::Web::RegObj;
use EnsEMBL::Web::Document::WebPage;
use EnsEMBL::Web::Document::Panel::InformationFragment;
use EnsEMBL::Web::Root;
use EnsEMBL::Web::Document::DropDown::MenuContainer;

my $cgi = new CGI;
my $incoming = $cgi->Vars;
my %params = ();
my %components = ();
my @ordered_componenents = ();

#warn "--------------------";
# warn("AJAX: Populating info fragment"); 

foreach my $key (keys %{ $incoming }) {
  #warn "KEY: " . $key . ": " . $incoming->{$key};
  if ($key =~ /^component_/) {
    push @ordered_componenents, $key;
    $components{$key} = $incoming->{$key};
  } else {
    $params{$key} = $incoming->{$key};
  }
}

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'use_proxy'  => 1,
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'geneview',
  'objecttype' => 'Gene',
);

my $gene = $webpage->dataObjects->[0];
my $fragment = EnsEMBL::Web::Document::Panel::InformationFragment->new(
  object => $gene,
  'code' => 'info',
  caption => 'AJAX fragment',
  status => 'loading',
  display => 'on',
);

#warn "GENE:" . $gene->stable_id;
$gene->script('geneview');
my $mc = $gene->new_menu_container(
  'configname' => 'altsplice',
  'panel'      => 'altsplice',
  'leftmenus' => ['Features']     );

#warn $mc->render_js_old;
my $json_components = "";
foreach my $component (@ordered_componenents) {
  
  $components{$component} =~ m/(.*)::(.*)$/;
  my $module = $1;
  my $method = $2;
  if (EnsEMBL::Web::Root::dynamic_use($module, $module)) {
    no strict "refs";
    my $execute = $components{$component};
    my $result = &$execute($fragment, $gene);
    $json_components = $component; 
    use strict "refs";
  } else {
    #warn "NOT LOADED: " . $module;
  }
}

print "Content-type: text/plain\n\n";
my $json_string = "{ status:'Load complete for info', component:'$json_components', html:'" . $fragment->html . "', menu:{ width:'" . $mc->{'menuwidth'} . "'} }";
print $json_string;

1;
