#!/usr/local/bin/perl

use EnsEMBL::Web::Document::WebPage;
use ExaLead::Renderer::HTML;
use ExaLead;
use strict;
use Time::HiRes qw(time);
use Data::Dumper;
use CGI
$Data::Dumper::Indent = 1;

my $page = new EnsEMBL::Web::Document::WebPage;

my $exalead = new ExaLead;
   $exalead->engineURL = $page->{'species_defs'}->ENSEMBL_SEARCH_URL; 
   $exalead->rootURL   = "/$ENV{'ENSEMBL_SPECIES'}/searchview";
my $q = CGI->new();

( my $SPECIES   = $ENV{'ENSEMBL_SPECIES'} ) =~ s/_/ /g;

my $source = "+Top/Source/" . $page->{'species_defs'}->ENSEMBL_EXALEAD_SITE_INDEX;

my $not_fresh = $q->param;
if( $not_fresh ) {
  if( $q->param('q') ) {
    $q->param('_q',$q->param('q'));
    my $CAT = '';
    my $CAT2 = '';
    if( $q->param('species') && $q->param('species') ne 'all' ) {
      $CAT = "Top/Species/".$q->param('species');
      if ( $q->param('idx') && $q->param('idx') ne 'All' ) {
        $CAT .= '/'.$q->param('idx');
        $CAT2 = "Top/Feature type/".$q->param('idx').'/'.$q->param('species');
      }
    } elsif( $q->param('idx') && $q->param('idx') ne 'All' ) {
      $CAT = "Top/Feature type/".$q->param('idx');
    }
    if( $CAT ) {
      $CAT =~ s/_/ /g;
      if( $CAT2 ) {
        $CAT2 =~ s/_/ /g;
        $q->param('_c', "+$CAT2", "+$CAT","$source" );
      } else {
        $q->param('_c', "+$CAT" , "$source");
      }
    } else {
      $q->param( '_c', "$source" );
    }
  } elsif( $q->param('_q') ){
    $q->param('_c', "$source");
  }
  $exalead->parse( $q );
}

my $renderer = new ExaLead::Renderer::HTML( $exalead );

my $sitetype = $page->{'species_defs'}->ENSEMBL_SITE_NAME;
my $panel = new EnsEMBL::Web::Document::Panel(
  'caption' => "$sitetype text search",
  'content' => $renderer->render_form. 
               $renderer->render_spelling.
    $renderer->render_summary.
    $renderer->render_navigation.
    $renderer->render_hits
);
$page->page->content->add_panel($panel);

if( 0 ) {
use XML::Simple;
$page->page->content->add_panel( new EnsEMBL::Web::Document::Panel(
  'caption' => 'RAW',
  'content' => '<pre>'.  CGI::escapeHTML(XMLout($exalead->{'XML'},'KeyAttr'=>{})).'</pre>'
));
}
foreach my $group ( $renderer->exalead->groups ) {
  my $block_name = CGI::escapeHTML( $group->name );
  if( $group->link( 'reset' ) ) {
    $block_name =  sprintf qq(<a href="%s"><img align="top" src="/img/14-r.gif" height="14" width="14" alt="[R]" border="0" /></a> %s\n), $group->link( 'reset' )->URL, $block_name;
  }
  my $block_content = '<dl>';
  foreach my $category ( sort {$a->name cmp $b->name} $group->children ) {
    $block_content .= render_category( $renderer, $category, 0 );
  }
  $block_content .= '</dl>';
  $page->page->menu->add_block( $group->name, 'raw', $block_name, 'html' => $block_content, 'raw'=>1 );
}

if( $renderer->exalead->keywords ) {
  my $block_content = '<dl>';
  foreach my $keyword ( sort { $a->name cmp $b->name } $renderer->exalead->keywords ) {
    $block_content .= _render_category( $keyword, 0 );
  }
  $block_content .= "</dl>\n";
  $page->page->menu->add_block( 'keywords', 'raw', 'Keywords', 'html' => $block_content, 'raw'=>1 );
}

 $page->page->menu->add_block( 'exalead_help', 'raw', 'Exalead Help', 'html' => qq(<div style="font-size: 0.8em">
<p>
  To exclude a category click on the "<img align="top" src="/img/14-m.gif" height="14" width="14" alt="[-]" border="0" />".
</p>
<p>
  To restrict to a category click on the name of the category.
</p>
<p>
  To reset a category click on the "<img align="top" src="/img/14-r.gif" height="14" width="14" alt="[R]" border="0" />" or it's name.
</p></div>)
 );
$q->header;
$page->page->render();

sub render_category {
  my( $renderer, $category, $level ) = @_;
  my $out = _render_category( $category, $level );
  foreach my $cat2 ( sort { $a->name cmp $b->name } $category->children ) {
    $out .= render_category( $renderer, $cat2, $level+1 );
  }
  return $out;
}

sub _render_category {
  my( $category, $level ) = @_;
  my $out = '';
  if( $category->link( 'reset' ) ) {
    $out = sprintf qq(<dt style="margin-left: %fem"><a href="%s"><img align="top" src="/img/14-r.gif" height="14" width="14" alt="[R]" border="0" /></a> <a href="%s">%s</a>),
      $level * 2,
      $category->link( 'reset' )->URL,
      $category->link( 'reset' )->URL,
      CGI::escapeHTML( $category->name );
  } else {
    $out = sprintf qq(<dt style="margin-left: %fem"><a href="%s"><img align="top" src="/img/14-m.gif" height="14" width="14" alt="[-]" border="0" /></a> <a href="%s">%s</a>),
      $level * 2,
      $category->link( 'exclude' )->URL,
      $category->link( 'refine' )->URL,
      CGI::escapeHTML( $category->name );
  }
  if( $category->count > 0 ) {
    $out .= sprintf( " (%d)", $category->count );
  }
  return "$out</dt>\n";
}

1;
