<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Homo sapiens</i></b></td>
<th class="bg4 center" style="width:5em"><i>H.sap</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Pan troglodytes</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<th class="bg1 center" style="width:5em"><i>P.tro</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Macaca mulatta</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<th class="bg4 center" style="width:5em"><i>M.mul</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Mus musculus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<th class="bg1 center" style="width:5em"><i>M.mus</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Rattus norvegicus</i></b></td>
<td class="bg4 center"><font color="blue">YES (on R.nor)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center"><font color="blue">YES (on R.nor)</font></td><!-- M.mus -->
<th class="bg4 center" style="width:5em"><i>R.nor</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Cavia porcellus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<th class="bg1 center" style="width:5em"><i>C.por</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Oryctolagus cuniculus</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<th class="bg4 center" style="width:5em"><i>O.cun</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Felis catus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<th class="bg1 center" style="width:5em"><i>F.cat</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Canis familiaris</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center"><font color="blue">YES (on M.mus)</font></td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center"><font color="blue">YES</font></td><!-- F.cat -->
<th class="bg4 center" style="width:5em"><i>C.fam</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Bos taurus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<th class="bg1 center" style="width:5em"><i>B.tau</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Dasypus novemcinctus</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<th class="bg4 center" style="width:5em"><i>D.nov</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Echinops telfairi</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<th class="bg1 center" style="width:5em"><i>E.tel</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Loxodonta africana</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg4 center">-</td><!-- D.nov -->
<td class="bg3 center">-</td><!-- E.tel -->
<th class="bg4 center" style="width:5em"><i>L.afr</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Sorex araneus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<td class="bg1 center">-</td><!-- E.tel -->
<td class="bg3 center">-</td><!-- L.afr -->
<th class="bg1 center" style="width:5em"><i>S.ara</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Otolemur garnettii</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg4 center">-</td><!-- D.nov -->
<td class="bg3 center">-</td><!-- E.tel -->
<td class="bg4 center">-</td><!-- L.afr -->
<td class="bg3 center">-</td><!-- S.ara -->
<th class="bg4 center" style="width:5em"><i>O.gar</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Spermophilus tridecemlineatus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<td class="bg1 center">-</td><!-- E.tel -->
<td class="bg3 center">-</td><!-- L.afr -->
<td class="bg1 center">-</td><!-- S.ara -->
<td class="bg3 center">-</td><!-- O.gar -->
<th class="bg1 center" style="width:5em"><i>S.tri</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Myotis lucifugus</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg4 center">-</td><!-- D.nov -->
<td class="bg3 center">-</td><!-- E.tel -->
<td class="bg4 center">-</td><!-- L.afr -->
<td class="bg3 center">-</td><!-- S.ara -->
<td class="bg4 center">-</td><!-- O.gar -->
<td class="bg3 center">-</td><!-- S.tri -->
<th class="bg4 center" style="width:5em"><i>M.luc</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Erinaceus europaeus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<td class="bg1 center">-</td><!-- E.tel -->
<td class="bg3 center">-</td><!-- L.afr -->
<td class="bg1 center">-</td><!-- S.ara -->
<td class="bg3 center">-</td><!-- O.gar -->
<td class="bg1 center">-</td><!-- S.tri -->
<td class="bg3 center">-</td><!-- M.luc -->
<th class="bg1 center" style="width:5em"><i>E.eur</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Tupaia belangeri</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg4 center">-</td><!-- D.nov -->
<td class="bg3 center">-</td><!-- E.tel -->
<td class="bg4 center">-</td><!-- L.afr -->
<td class="bg3 center">-</td><!-- S.ara -->
<td class="bg4 center">-</td><!-- O.gar -->
<td class="bg3 center">-</td><!-- S.tri -->
<td class="bg4 center">-</td><!-- M.luc -->
<td class="bg3 center">-</td><!-- E.eur -->
<th class="bg4 center" style="width:5em"><i>E.eur</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Monodelphis domestica</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<td class="bg1 center">-</td><!-- E.tel -->
<td class="bg3 center">-</td><!-- L.afr -->
<td class="bg1 center">-</td><!-- S.ara -->
<td class="bg3 center">-</td><!-- O.gar -->
<td class="bg1 center">-</td><!-- S.tri -->
<td class="bg3 center">-</td><!-- M.luc -->
<td class="bg1 center">-</td><!-- E.eur -->
<td class="bg3 center">-</td><!-- E.eur -->
<th class="bg1 center" style="width:5em"><i>M.dom</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Ornithorhynchus anatinus</i></b></td>
<td class="bg4 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center"><font color="blue">YES (on M.mus)</font></td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- C.por -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- F.cat -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg4 center">-</td><!-- D.nov -->
<td class="bg3 center">-</td><!-- E.tel -->
<td class="bg4 center">-</td><!-- L.afr -->
<td class="bg3 center">-</td><!-- S.ara -->
<td class="bg4 center">-</td><!-- O.gar -->
<td class="bg3 center">-</td><!-- S.tri -->
<td class="bg4 center">-</td><!-- M.luc -->
<td class="bg3 center">-</td><!-- E.eur -->
<td class="bg4 center">-</td><!-- E.eur -->
<td class="bg3 center">-</td><!-- M.dom -->
<th class="bg4 center" style="width:5em"><i>O.ana</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Gallus gallus</i></b></td>
<td class="bg3 center"><font color="blue">YES (on H.sap)</font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- C.por -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- F.cat -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- D.nov -->
<td class="bg1 center">-</td><!-- E.tel -->
<td class="bg3 center">-</td><!-- L.afr -->
<td class="bg1 center">-</td><!-- S.ara -->
<td class="bg3 center">-</td><!-- O.gar -->
<td class="bg1 center">-</td><!-- S.tri -->
<td class="bg3 center">-</td><!-- M.luc -->
<td class="bg1 center">-</td><!-- E.eur -->
<td class="bg3 center">-</td><!-- E.eur -->
<td class="bg1 center">-</td><!-- M.dom -->
<td class="bg3 center">-</td><!-- O.ana -->
<th class="bg1 center" style="width:5em"><i>G.gal</i></th>
</tr>

</table>

<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Takifugu rubripes</i></b></td>
<th class="bg4 center" style="width:5em"><i>T.rub</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Tetraodon nigroviridis</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- T.rub -->
<th class="bg1 center" style="width:5em"><i>T.nig</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Gasterosteus aculeatus</i></b></td>
<td class="bg4 center">-</td><!-- T.rub -->
<td class="bg3 center">-</td><!-- T.nig -->
<th class="bg4 center" style="width:5em"><i>G.acu</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Oryzias latipes</i></b></td>
<td class="bg3 center">-</td><!-- T.rub -->
<td class="bg1 center">-</td><!-- T.nig -->
<td class="bg3 center"><font color="blue">YES (on O.lat)</font></td><!-- G.acu -->
<th class="bg1 center" style="width:5em"><i>O.lap</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Ciona intestinalis</i></b></td>
<td class="bg4 center">-</td><!-- T.rub -->
<td class="bg3 center">-</td><!-- T.nig -->
<td class="bg4 center">-</td><!-- G.acu -->
<td class="bg3 center">-</td><!-- O.lap -->
<th class="bg4 center" style="width:5em"><i>C.int</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Ciona savignyi</i></b></td>
<td class="bg3 center">-</td><!-- T.rub -->
<td class="bg1 center">-</td><!-- T.nig -->
<td class="bg3 center">-</td><!-- G.acu -->
<td class="bg1 center">-</td><!-- O.lap -->
<td class="bg3 center"><font color="blue">YES (on C.int)</font></td><!-- C.int -->
<th class="bg1 center" style="width:5em"><i>C.sav</i></th>
</tr>

<tr>
<th></th>
<th class="bg3 center" style="width:5em"><i>T.rub</i></th>
<th class="bg1 center" style="width:5em"><i>T.nig</i></th>
<th class="bg3 center" style="width:5em"><i>G.acu</i></th>
<th class="bg1 center" style="width:5em"><i>O.lap</i></th>
<th class="bg3 center" style="width:5em"><i>C.int</i></th>
<th class="bg1 center" style="width:5em"><i>C.sav</i></th>
<th></th>
</tr>

</table>
