#!/usr/local/bin/perl
package transview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Input::CGI;
use EnsEMBL::Web::Output::HTML;
use EnsEMBL::Web::DataFactory::TranscriptFactory;
use EnsEMBL::DB::DBConnection;              

$| = 1; 

my $input  = EnsEMBL::Web::Input::CGI->new('transview');    
my $output = EnsEMBL::Web::Output::HTML->new();
my $dbs    = EnsEMBL::DB::DBConnection->new($input->species);

$input->initialise_from_cgi;
$input->param('show_vega_markup',[1]);
$input->param('show_vega_evidence_link',[1]);

my $transFactory = EnsEMBL::Web::DataFactory::TranscriptFactory->new(   
        $dbs, 
        $input,
        $output
);
$transFactory->createObjects();   

if ($transFactory->has_a_problem) {   
    if ($transFactory->has_problem_type('mapped_id') || $transFactory->has_problem_type('multiple_matches')){
        my $transcript = $transFactory->featureIds->[0];
        my $db = $input->param('db') || 'core' ;
        $output->page_redirect("/$ENV{'ENSEMBL_SPECIES'}/$ENV{'ENSEMBL_SCRIPT'}?transcript=$transcript&db=$db");
    } else {
        $output->error_page($transFactory->problem->[0]) ; 
        $output->ensembl_exit;
    }
} else {
    $output->start; 
    for my $trans_data (@{$transFactory->DataObjects}) {
        my $transcript_renderer = $trans_data->renderer;
        $transcript_renderer->Output->generic_table_title('Vega Transcript Report');
        $transcript_renderer->Output->print_two_col_table(
            $transcript_renderer->transcript_display_ID,
            $transcript_renderer->vega_stable_id,
            $transcript_renderer->version,
            $transcript_renderer->transcript_class,
            $transcript_renderer->other_view_links('Transcript Information'),
            $transcript_renderer->genomic_location,
            $transcript_renderer->description,
            $transcript_renderer->remarks,
            $transcript_renderer->author,
            $transcript_renderer->similarity_matches('Database Matches'),
            $transcript_renderer->interpro_links,
            $transcript_renderer->exportview_link,
        );
        $transcript_renderer->outputTransviewPageBottom();      
    }
    $output->end;
}

use Bio::EnsEMBL::Registry; Bio::EnsEMBL::Registry->disconnect_all();1;

1;
