#!/usr/bin/perl
# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# Copyright [2016-2022] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


package martview;

use strict;
use warnings;
use CGI;

my $cgi = new CGI;
my %params = %{ $cgi->Vars };

my $biomart_url = "http://www.ensembl.org/biomart/martview?";

foreach my $key (keys %params) {
    if ($params{$key}) {
	$biomart_url .= $key . "=" . $params{$key};
    }
}

$cgi->redirect($biomart_url);

1;

 
