#!/usr/bin/env perl

=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2017] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

### Only builds the packed file if they are missing.

use strict;
use warnings;

use FindBin qw($Bin);

BEGIN {
  require "$Bin/helper.pl";

  my $config_file = sprintf '%s/conf/%s', $SiteDefs::ENSEMBL_SYS_DIR, $SiteDefs::ENSEMBL_CONFIG_FILENAME;

  if (-e $config_file) {
    if (unlink $config_file) {
      warn "Removed $config_file\n";
    } else {
      die("Could not remove conf file: $config_file\n");
    }
  }
}

use EnsEMBL::Web::SpeciesDefs;

EnsEMBL::Web::SpeciesDefs->new();

1;
