#!/usr/bin/env perl

=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2017] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

use strict;
use warnings;

use Getopt::Long;
use FindBin qw($Bin);
use Storable qw(retrieve);
use JSON qw(to_json);
use Storable qw(freeze);

BEGIN {
  require "$Bin/helper.pl";
};

my $format = 'json';
GetOptions('format=s' => \$format);
$format = lc($format);

my $data = {
  SiteDefs => {},
};

foreach my $k (keys %SiteDefs::) {
  $data->{'SiteDefs'}{$k} = ${$SiteDefs::{$k}};
}

my $packed_fn = "$SiteDefs::ENSEMBL_SYS_DIR/conf/$SiteDefs::ENSEMBL_CONFIG_FILENAME";

$data->{'packed'} = retrieve($packed_fn);

sub cleanup {
  my ($x) = @_;

  if(ref($x) eq 'HASH') {
    $x->{$_} = cleanup($x->{$_}) for keys %$x;
  } elsif(ref($x) eq 'ARRAY') {
    $x = [ map { cleanup($_) } @$x ];
  } elsif(ref($x)) {
    return undef;
  }
  return $x;
}

$data = cleanup($data);

if($format eq 'json') {
  print to_json($data);
} elsif($format eq 'storable') {
  print freeze($data);
}

1;
