#!/usr/local/bin/perl

=head1 NAME

start_server - script to start an Ensembl server

=head1 SYNOPSIS

    ctrl_scripts/start_server [-rXh]

=head1 DESCRIPTION

This script starts up an Ensembl server. Available options are:

    - delete conf/config.packed before start
    - start Apache in single server mode

Run 'ctrl_script/start_server --help' for usage details.

=head1 LICENCE

This code is distributed under an Apache style licence:
Please see http://www.ensembl.org/code_licence.html for details

=head1 AUTHOR

Patrick Meidl <pm2@sanger.ac.uk>

=head1 CONTACT

Post questions to the EnsEMBL development list ensembl-dev@ebi.ac.uk

=cut

use strict;
use warnings;
no warnings 'uninitialized';

use FindBin qw($Bin);
use File::Basename qw( dirname );
use Sys::Hostname::Long;
use Getopt::Long;

my ($help, $rmconfig, $single, $flush);
my $serverroot;

BEGIN {
  $serverroot = dirname($Bin);
  unshift @INC, "$serverroot/conf";
};

use SiteDefs;

my $confdir = 'conf';
&GetOptions(
  "confdir=s"       => \$confdir,
  "rmconfig"      => \$rmconfig,
  "r"             => \$rmconfig,
  "flush"         => \$flush,
  "f"             => \$flush,
  "X"             => \$single,
  "single"        => \$single,
  "help"          => \$help,
  "h"             => \$help,
);

warn "
==============================================================================
 Starting server with configurations from $confdir
";

if ($help) {
  print qq(
	Usage:
    ctrl_scripts/start_server
      [-r|--rmconfig]
      [-f|--flush]
      [-X|--single]
      [-h|--help]
        
Options:
  -r, --rmconfig  : remove conf/config.packed before restarting the server and flush memcached
	-f, --flush     : flush memcached storage!
  -X, --single    : start Apache in single server mode
  -h, --help      : print this help message
);
    exit;
}

my $hostname = hostname_long();

# start the server
if ($rmconfig) {
  warn " Removing config.packed...\n";
  my $ok = unlink "$serverroot/$confdir/config.packed";
  if ($ok) {
    warn " Removed config.packed....\n";
  } else {
    warn " Could not delete $serverroot/$confdir/config.packed: $!\n[WARN] Starting with old config.packed!\n";
  }
}

## Check memcached servers version
  warn " Checking memcached compatibility...\n";
  my $res = system("perl $serverroot/utils/memd.pl version");
  if ($res >> 8 > 0) {
    die " failed\nPlease check www.ensembl.org/info/docs/webcode/memcached\n";
  }


if( $flush || $rmconfig ) {
  # Flush memcached
  ## TODO: kill the hack // looks like it's not a hack anymore
  ## HACK: add extra tag for everything except user upload data	
  my $cmd = "perl $serverroot/utils/memd.pl flush";
  my @res = `$cmd`; chomp @res;
  warn " Flushed memcached entries for this server (@res)\n";
}
warn "==============================================================================\n";

# LOAD LSF ENVIRONMENT - REQUIRED FOR BLAST
my $cmd = ". /usr/local/lsf/conf/profile.lsf;" if -e '/usr/local/lsf/conf/profile.lsf';

$cmd .= $SiteDefs::APACHE_DIR."/bin/httpd -d ".$SiteDefs::APACHE_DIR." -f $serverroot/$confdir/httpd.conf" . ($single ? " -X &" : "");

exec($cmd) or die " Could not start server: $!.\n[FATAL] Server start failed.\n";

