#!/usr/bin/env perl

=head1 NAME

taillog - script to tail -f the current log

=head1 SYNOPSIS

    ctrl_scripts/taillog [--access] 

=head1 DESCRIPTION

This script starts a "tail -f" on the current apache log.
By default, it tails the latest error log for the current host, but
specifying --access tails the access log instead

=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2021] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=head1 AUTHOR

Jim Stalker <jws@sanger.ac.uk>

=cut

use strict;
use warnings;
no warnings 'uninitialized';

use Getopt::Long;
use FindBin qw($Bin);

BEGIN {
  require "$Bin/helper.pl";
}

my ($help, $do_access, $both, $do_nginx);
&GetOptions(
  "nginx"   => \$do_nginx,
  "access"  => \$do_access,
  "both"    => \$both,
  "h"       => \$help,
);
die '
------------------------------------------------------------------------
Usage:
  ctrl_scripts/taillog
    [-a|--access]
    [-b|--both]
    [-h|--help]
        
Options:
  -a, --access    : Tails access log instead of error log
  -b, --both      : Tails access and error log (using multitail)
  -h, --help      : print this help message

Notes:
  For -b to work must have multitail installed
  http://www.vanheusden.com/multitail/
	
------------------------------------------------------------------------
' if $help;

my ($al) = split /\s+/, ( $SiteDefs::ENSEMBL_CUSTOMLOG );
my $el = $SiteDefs::ENSEMBL_ERRORLOG;

if( $do_nginx ) {
  $al = $SiteDefs::ENSEMBL_LOGDIR.'/nginx.access_log';
  $el = $SiteDefs::ENSEMBL_LOGDIR.'/nginx.error_log';
}

my $cmd = '';
if( $both ) {
  $cmd = "multitail -o check_mail:0 --mergeall -ci yellow,,bold $al $el";
} elsif( $do_access ) {
  $cmd = "tail -f $al";
} else {
  $cmd = "tail -f $el";
}
exec($cmd) or die "Could not tail log: $!.\n";

