#!/usr/local/bin/perl

package transview_tn;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'scriptname' => 'transview',
  'objecttype' => 'Transcript',
);
if( $webpage->has_a_problem() ) {
  if( $webpage->has_problem_type('mapped_id') ) {
    my $feature = $webpage->factory->__data->{'objects'}[0];
    $webpage->redirect( "/$ENV{'ENSEMBL_SPECIES'}/$ENV{'ENSEMBL_SCRIPT'}?".join(';',map {"$_=$feature->{$_}"} keys %$feature ) );
  } else {
    $webpage->render_error_page( $webpage->problem->[0] );
  }
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'transview_tn', 'context_menu', 'context_location' );
  }
  $webpage->render();
}

1;
