#!/usr/local/bin/perl

package BACmap;

use strict;
use CGI qw(:standard :html3 :cookie);
use EnsWeb;

my $cgi = new CGI;

my $chr	= $cgi->param('chr');
my $band	= $cgi->param('band');
my $img_path = '/gfx/Anopheles_gambiae/BAC_map';

print &CGI::header();
print &EnsWeb::make_cgi_header(('initfocus'=>1,'menus'=>1));

if (-e EnsWeb::species_defs->ENSEMBL_SERVERROOT.qq(/htdocs$img_path/$chr\_$band\_small.gif)){
print qq(
<br />
<TABLE align="center" border="0" cellpadding="0" cellspacing="0" width="650" class="background1">
 <tr class="black" valign="top">
  <td rowspan="5"><img src="/gfx/blank.gif" height="1" alt=""></td>
  <td><img src="/gfx/blank.gif" height="1" width="548" alt=""></td>
  <td rowspan="5"><img src="/gfx/blank.gif" height="1" alt=""></td>
 </tr>
 <tr class="background2">
  <td class="h4" align="center">Chromosome BAC Map Diagram
  </td>
 </tr>
 <tr class="black" valign="top">
  <td><img src="/gfx/blank.gif" height="1" width="1" alt=""></td>
 </tr>
 <tr>
  <td>
	 
   <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" class="background1">
    <tr>
     <td colspan="3"><br />The following image show a diagrammatic representation of the Anopheles
	 $chr chromosome at band $band with BAC positions mapped to the image.<br /><br /></td>
    </tr>

    <tr valign="top" class="background2">
     <td align="left"><img src="/gfx/topleft.gif" height="16" width="16" alt=""></td>
     <td align="center" class="h5" nowrap>Chromosome $chr - Band $band</td>
     <td align="right"><img src="/gfx/topright.gif" height="16" width="16" alt=""></td>
    </tr>

    <tr>
     <td><img src="/gfx/blank.gif" height="5" width="16" alt=""></td>
     <td><img src="/gfx/blank.gif" height="5" width="368" alt=""></td>	 
     <td><img src="/gfx/blank.gif" height="5" width="16" alt=""></td>	 
    </tr>
	<TR>
        <TD><IMG height=16 alt="" src="/gfx/blank.gif"width=16></TD>
     	<TD align="center"><img src="$img_path/$chr\_$band\_small.gif" hspace=10 
		vspace=5 alt="$chr-$band" border="0" ></TD>
		 <TD>&nbsp;</TD>
     </TR>
              	 	      			      
     <tr>
     <td colspan="2"><img src="/gfx/blank.gif" height="5" width="498" alt=""></td>
	 <td>&nbsp;<br /></td>
	 <TD>&nbsp;</TD>
    </tr>
   </table>
	  
  </td>
 </tr>
 <tr class="black" valign="top">
  <td><img src="/gfx/blank.gif" height="1" alt=""></td>
 </tr>
</TABLE>  

<br />
);

}else{
&ensembl_warning("Invalid Chromosome Band", "The band name you have entered does not exists.") ;
}

print EnsWeb::make_cgi_footer();
