#!/usr/local/bin/perl

package transposub;
use EnsEMBL::Web::TransposonSubmission;

my $transposub = new EnsEMBL::Web::TransposonSubmission;

my $action = "ACTION_".$transposub->parameter('action');
   $action = "ACTION_main" unless $transposub->can($action);

$transposub->$action;

1;
