=head1 LICENSE

Copyright [1999-2014] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

package EnsEMBL::Web::File::Dynamic;

use strict;

use parent qw(EnsEMBL::Web::File);

### Replacement for EnsEMBL::Web::TmpFile::Image and (in part) 
### E::W::TmpFile::Text, specifically for content generated by dynamic
### pages for display on the Ensembl website.

### Data can be written to disk or, if enabled and appropriate, memcached

### Path structure: /base_dir/YYYY-MM-DD/user_identifier/XXXXXXXX/filename.ext

sub new {
### @constructor
  my ($class, %args) = @_;
  $args{'input_drivers'}  ||= [qw(Memcached IO)];
  $args{'output_drivers'} ||= [qw(Memcached IO)];
  my $sd = $args{'hub'}->species_defs;
  $args{'base_dir'} = $sd->ENSEMBL_TMP_DIR_IMG; 
  $args{'base_url'} = $sd->ENSEMBL_STATIC_SERVER . $sd->ENSEMBL_TMP_URL_IMG;
  return $class->SUPER::new(%args);
}

1;

