=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2021] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

package EnsEMBL::Web::File::Dynamic;

use strict;

use parent qw(EnsEMBL::Web::File);

### Replacement for EnsEMBL::Web::TmpFile::Image and (in part) 
### E::W::TmpFile::Text, specifically for content generated by dynamic
### pages for display on the Ensembl website.

### Data can be written to disk or, if enabled and appropriate, memcached

### Path structure: /base_dir/YYYY-MM-DD/XXXXXXXX/filename.ext

sub new {
### @constructor
  my ($class, %args) = @_;
  my $ok_drivers = ['IO'];
  if ($args{'hub'} && keys %{$args{'hub'}->species_defs->ENSEMBL_MEMCACHED||{}}) {
    unshift @$ok_drivers, 'Memcached';
  }
  $args{'input_drivers'}  ||= $ok_drivers;
  $args{'output_drivers'} ||= $ok_drivers;
  $args{'base_dir'} = 'image'; 
  return $class->SUPER::new(%args);
}

sub set_user_identifier {
  ### Don't set user id, otherwise caching is pointless and also
  ### we can't serve images to external browser-less services
  return undef;
}

sub read_url {
  my $self = shift;
  my $path = $self->SUPER::read_url(@_);
  return $self->{'absolute'} ? $path : $self->hub->species_defs->ENSEMBL_STATIC_SERVER.$path;
}

sub write_url {
  my $self = shift;
  my $path = $self->SUPER::write_url(@_);
  return $self->{'absolute'} ? $path : $self->hub->species_defs->ENSEMBL_STATIC_SERVER.$path;
}


1;

