#!/usr/local/bin/perl

# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# Copyright [2016-2021] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BEGIN {
  (my $ensembl_root=$0) =~ s#/dump.*##;
  $ensembl_root = $ensembl_root eq '.' ? '..' : '.' unless $ensembl_root =~ s#/[^/]*$##;
  my @paths = qw( conf modules ensembl/modules ensembl-external/modules ensembl-compara/modules ensembl-variation/modules ensembl-otter/modules );
  foreach( @paths ) { unshift @INC, "$ensembl_root/$_"; }
};

use EnsEMBL::Web::SpeciesDefs;
my $conf = EnsEMBL::Web::SpeciesDefs->new();
$conf->retrieve();

print "#"x78,"\n## _storage ","#"x66,"\n","#" x 78,"\n\n";
$conf->dump(\*STDOUT, 0, $conf->{'_storage'});
print "\n", "#"x78,"\n## _multi   ","#"x66,"\n","#" x 78,"\n\n";
$conf->dump(\*STDOUT, 0, $conf->{'_multi'});
print "\n", "#"x78,"\n\n";

