#!/usr/bin/perl

# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# Copyright [2016-2021] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use CGI qw(unescape);

use FindBin qw($Bin);

BEGIN{
  unshift @INC, "$Bin/../conf";
  unshift @INC, "$Bin/../modules";
  eval{ require SiteDefs; SiteDefs->import; };
  if ($@){ die "Can't use SiteDefs.pm - $@\n"; }
}

my( $log, $type ) = split / /, $SiteDefs::ENSEMBL_CUSTOMLOG;
open I, "tail -f $log|";

my $regexp = shift @ARGV ;#? '('.join( '|', map { quotemeta $_ } @ARGV ).')' : '';

while(<I>) { 
  next unless /^\[\d+ (\d+\.\d+).*?"(GET|POST) (\S+) HTTP\/1\.[01]" (\d+) (-|\d+)/;
  my ($time, $method, $url, $status, $bytes ) = ($1,$2,$3,$4,$5);
  next if $regexp && ($regexp ne '\?' || $method ne 'POST' ) && ($url!~/$regexp/o);
  my $parsed = parse( $url );
 
  printf "%10.6f %5d %8d %s\n", $time, $status, $bytes, $parsed->{'url'};
  foreach ( sort keys %{$parsed->{'params'}} ) {
    printf " %25s = %s\n",
      $_, join( "; ",@{$parsed->{'params'}{$_}});
  }
}

sub parse {
  my $request = shift;
  my ($url,$query_string) = split /\?/, $request,2;
  $url = $1 if $url =~ /^https?:\/\/.*?(\/.*)$/;
  my(@pairs) = split(/[&;]/,$query_string);
  my $params = {};
  foreach (@pairs) {
    my($param,$value) = split('=',$_,2);
    next unless defined $param;
    $value = '' unless defined $value;
    $param = CGI::unescape($param);
    $value = CGI::unescape($value);
    push @{$params->{$param}}, $value;
  }
  return {
    'url'    => $url,
    'params' => $params
  };
}
