#! /usr/local/bin/perl

package account;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

## Login basics
$controller->add_connections({qw(
  Login              EnsEMBL::Web::Controller::Command::Account::LogIn
  SetCookie          EnsEMBL::Web::Controller::Command::Account::SetCookie
  Logout             EnsEMBL::Web::Controller::Command::Account::LogOut
)});

## Accountview
$controller->add_connections({qw(
  Links              EnsEMBL::Web::Controller::Command::Account::Links 
  Bookmarks          EnsEMBL::Web::Controller::Command::Account::Bookmarks 
  Configurations     EnsEMBL::Web::Controller::Command::Account::Configurations
  Annotations        EnsEMBL::Web::Controller::Command::Account::Annotations
  NewsFilters        EnsEMBL::Web::Controller::Command::Account::NewsFilters 
)});

## Account management 
$controller->add_connections({qw(
  Summary            EnsEMBL::Web::Controller::Command::Account::Details
  Register           EnsEMBL::Web::Controller::Command::Account::Register
  RegistrationFailed EnsEMBL::Web::Controller::Command::Account::RegistrationFailed 
  SendActivation     EnsEMBL::Web::Controller::Command::Account::SendActivation 
  EmailSent          EnsEMBL::Web::Controller::Command::Account::EmailSent 
  Activate           EnsEMBL::Web::Controller::Command::Account::Activate 
  Details            EnsEMBL::Web::Controller::Command::Account::Details 
  LostPassword       EnsEMBL::Web::Controller::Command::Account::LostPassword 
  ChangePassword     EnsEMBL::Web::Controller::Command::Account::ChangePassword 
  SavePassword       EnsEMBL::Web::Controller::Command::Account::SavePassword 
  Update             EnsEMBL::Web::Controller::Command::Account::Update 
  UpdateFailed       EnsEMBL::Web::Controller::Command::Account::UpdateFailed 
)});

## User records
$controller->add_connections({qw(
  SaveFavourites     EnsEMBL::Web::Controller::Command::Account::SaveFavourites 
  ResetFavourites    EnsEMBL::Web::Controller::Command::Account::ResetFavourites 
  Sortable           EnsEMBL::Web::Controller::Command::Account::Sortable 

  Bookmark           EnsEMBL::Web::Controller::Command::Account::Bookmark 
  BookmarkLanding    EnsEMBL::Web::Controller::Command::Account::BookmarkLanding
  UseBookmark        EnsEMBL::Web::Controller::Command::Account::UseBookmark

  Configuration      EnsEMBL::Web::Controller::Command::Account::Configuration 
  LoadConfig         EnsEMBL::Web::Controller::Command::Account::LoadConfig 
  SetConfig          EnsEMBL::Web::Controller::Command::Account::SetConfig 
  ConfigLanding      EnsEMBL::Web::Controller::Command::Account::ConfigLanding

  Annotation         EnsEMBL::Web::Controller::Command::Account::Annotation 
  NewsFilter         EnsEMBL::Web::Controller::Command::Account::FilterNews 
)});

## Group records & group management
$controller->add_connections({qw(
  MemberGroups       EnsEMBL::Web::Controller::Command::Account::MemberGroups 
  _accept            EnsEMBL::Web::Controller::Command::Account::AcceptInvitation 
  _unsubscribe       EnsEMBL::Web::Controller::Command::Account::Unsubscribe 

  AdminGroups        EnsEMBL::Web::Controller::Command::Account::AdminGroups 
  Group              EnsEMBL::Web::Controller::Command::Account::Group 
  _remove_group      EnsEMBL::Web::Controller::Command::Account::RemoveGroup 
  _change_status     EnsEMBL::Web::Controller::Command::Account::ChangeStatus 
  _change_level      EnsEMBL::Web::Controller::Command::Account::ChangeLevel 

  SelectGroup        EnsEMBL::Web::Controller::Command::Account::SelectGroup 
  ShareRecord        EnsEMBL::Web::Controller::Command::Account::ShareRecord 

  Invite             EnsEMBL::Web::Controller::Command::Account::Invite 
  _remove_invitation EnsEMBL::Web::Controller::Command::Account::RemoveInvitation 
)});

$controller->dispatch($ENV{'REQUEST_URI'});

}

1;
