#!/usr/local/bin/perl

package accountview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'accountview',
  'objecttype' => 'User',
  'access'     => {'login' => 1}, ## page only accessible to logged-in users
);

if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'accountview', 'context_menu', 'user_menu' );
  }
  $webpage->action(); 
}
1;
