#!/usr/local/bin/perl

package activate;

use CGI;

my $cgi = new CGI;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::RegObj;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;
$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

my $sd = EnsEMBL::Web::SpeciesDefs->new();
my $site_info = {};
my $sitetype = $sd->ENSEMBL_SITETYPE;
my $sitename = $sitetype eq 'EnsEMBL' ? 'Ensembl' : $sitetype;
$site_info->{'name'} = $sitename;
$site_info->{'base_url'}    = $sd->ENSEMBL_BASE_URL;
$site_info->{'mail_server'} = $sd->ENSEMBL_MAIL_SERVER;
$site_info->{'help_email'}  = $sd->ENSEMBL_HELPDESK_EMAIL;

if (!$cgi->param('welcome_email')) {
  my $user = EnsEMBL::Web::Object::User->new({ id => $cgi->param('id') });
  send_activation_email($user, $site_info, $cgi->param('group_id') );
} elsif ($cgi->param('welcome_email') eq 'yes') {
  my $user = EnsEMBL::Web::Object::User->new({ id => $cgi->param('id') });
  send_welcome_email($user, $site_info);
  if ($cgi->param('group_id')) {
    my $group = EnsEMBL::Web::Object::Group->new(( id => $cgi->param('group_id') ));
    $user->add_group($group);
    $user->save;
  }

}

$data->discover;
$data->populate($cgi->param('id'));
$page->data_definition($data);
$page->title("Activate your $sitename account");
$page->action('edit');
$page->send_params({ id => 'yes', salt => 'yes', password => 'yes' });
$page->on_complete('/common/set_cookie');
$page->on_error('/error/activate.html');

$page->add_configuration_element('conditional', 'salt');
$page->add_configuration_element('welcome_email', 'yes');

$page->add_display_element('name', "Name");
$page->add_display_element('email', "Email address");
$page->add_display_element('organisation', "Organisation");

$conditional = EnsEMBL::Web::Interface::FormDefinition->new();
$conditional->add_option({ 'conditional' => 1 });
if ($cgi->param('code')) {
  $page->add_text("<b>Thanks for confirming your email address.</b><br /><br /> To start using your new Ensembl user account, just choose a password below. You'll need to use this password each time you log in to Ensembl.");
  $conditional->add_value({ 'salt' => $cgi->param('code') });
  $page->add_configuration_element('salt', $cgi->param('code'), $conditional);
} else {
  $page->add_text("Before you can start using your Ensembl user account, you need to validate your email address. We've just send you an email containing an activation code. Enter this code below, and choose a password. You'll need to use this password each time you log in to Ensembl.");
  $page->add_form_element('salt', "Your activation code", $conditional);
}

if ($cgi->param('group_id')) {
  $page->add_configuration_element('group_id', $cgi->param('group_id'));
}

$page->add_form_element('password', "Your password");

EnsEMBL::Web::Document::DataView::simple('User', $page);

sub send_activation_email {
  my ($user, $site_info, $group_id) = @_;
  my $sitename = $site_info->{'name'};
  my $message = qq(
  Welcome to $sitename,

  Thanks for registering with $sitename.
  
  You just need to activate your account, using the activation code below:
  
  Activation code: ) . $user->salt . qq(
 
  Or by clicking on this link:
  ) . $site_info->{'base_url'} . qq(/common/activate?id=) . $user->id . qq(&code=) . $user->salt;

  if ($group_id) {
    $message .= "&group_id=" . $group_id;
  }

  $message .= qq(  


  Many thanks,

  The $sitename web team



  $sitename Privacy Statement: ) . $site_info->{'base_url'} . qq(/info/about/privacy.html
  );
  send_email($site_info, $user, "Your new $sitename account", $message);
}

sub send_welcome_email {
  my ($user, $site_info) = @_;
  my $sitename = $site_info->{'name'};
  my $message = qq(Welcome to $sitename.

  Your account has been activated! In future, you can log in to $sitename using your email address and the password you chose during registration:
  
  Email: ) . $user->email . qq( 

  More information on how to make the most of your account can be found here:

  ) . $site_info->{'base_url'} . qq(/info/about/accounts.html


  Many thanks,

  The $sitename web team



  $sitename Privacy Statement: ) . $site_info->{'base_url'} . qq(/info/about/privacy.html
  );
  send_email($site_info, $user, "Welcome to $sitename", $message);
}

sub send_email {
  my ($site_info, $user, $subject, $message) = @_;
  warn "Sending email to: " . $user->email . " on " . $site_info->{'mail_server'};
  my $mailer = new Mail::Mailer 'smtp', Server => $site_info->{'mail_server'};
  $mailer->open({
                'To'      => $user->email,
                'From'    => $site_info->{'name'},
                'Reply-To'=> $site_info->{'help_email'},
                'Subject' => $subject
                });
  print $mailer $message;
  $mailer->close();

}

1;
