#!/usr/local/bin/perl

package activate;

use CGI;

my $cgi = new CGI;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::SpeciesDefs;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $EnsEMBL::Web::Apache::Handlers::ENSEMBL_USER_DB_HANDLE;
$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

if (!$cgi->param('welcome_email')) {
  my $user = EnsEMBL::Web::Object::User->new({ id => $cgi->param('id') });
  send_activation_email($user);
} elsif ($cgi->param('welcome_email') eq 'yes') {
  my $user = EnsEMBL::Web::Object::User->new({ id => $cgi->param('id') });
  send_welcome_email($user);
  if ($cgi->param('group_id')) {
    my $group = EnsEMBL::Web::Object::Group->new(( id => $cgi->param('group_id') ));
    $user->add_group($group);
    $user->save;
  }
}


$data->discover;
$data->populate($cgi->param('id'));
$page->data_definition($data);
$page->title('Activate your Ensembl account');
$page->action('edit');
$page->send_params({ id => 'yes', salt => 'yes', password => 'yes' });
$page->on_complete('/common/set_cookie');
$page->on_error('/register/error.html');

$page->add_configuration_element('conditional', 'salt');
$page->add_configuration_element('welcome_email', 'yes');
$page->add_configuration_element('group_id', $cgi->param('group_id'));

$page->add_display_element('name', "User name");
$page->add_display_element('organisation', "Organisation");

$conditional = EnsEMBL::Web::Interface::FormDefinition->new();
$conditional->add_option({ 'conditional' => 1 });

$page->add_form_element('salt', "Your activation code", $conditional);
$page->add_form_element('password', "Your password");

EnsEMBL::Web::Document::DataView::simple('User', $page);

sub send_activation_email {
  my $user = shift;
  my $species_defs = EnsEMBL::Web::SpeciesDefs->new();
  my $message = qq(
  Hello,

  Thanks for registering with Ensembl. Before you can log in to your Ensembl
  account, you need to verify your email address. To do so, cut and paste the 
  activation code below into the activation page. 
  
  Activation code: ) . $user->salt . qq(
 
  Alternatively, you can just click on this link:
  ) . $species_defs->ENSEMBL_BASE_URL . qq(/common/activate?id=) . $user->id . qq(  

  If you have any problems, please don't hesitate to contact our help desk on
  helpdesk\@ensembl.org.

  Many thanks,

  The Ensembl team
  );
  send_email($user, "Your new Ensembl account", $message);
}

sub send_welcome_email {
  my $user = shift;
  my $message = qq(Welcome to Ensembl);
  send_email($user, "Welcome to Ensembl", $message);
}

sub send_email {
  my ($user, $subject, $message) = @_;
  warn "Sending email to: " . $user->email;
  my $mailer = new Mail::Mailer 'smtp', Server => "mail.sanger.ac.uk";
  $mailer->open({
                'To'      => $user->email,
                'From'    => "Ensembl",
                'Reply-To'=> "helpdesk\@ensembl.org",
                'Subject' => $subject
                });
  print $mailer $message;
  $mailer->close();

}

1;
