#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;
use EnsEMBL::Web::Component::Blast;
use EnsEMBL::Web::Object::BlastRequest;
use EnsEMBL::Web::Object::BlastTicket;
use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::DBSQL::BlastAdaptor;

warn("Updating BlastView"); 

my $T = new CGI;
my $ticket = $T->param('ticket');

my $queue_class = "EnsEMBL::Web::Queue::LSF";
my $species_defs = EnsEMBL::Web::SpeciesDefs->new();
my $DB = { 'NAME' => 'ensembl_blast',
           'USER' => 'ensadmin',
           'PASS' => 'ensembl',
           'HOST' => 'ensarc-1-08',
           'PORT' => '3306' };

my $blast_adaptor = EnsEMBL::Web::DBSQL::BlastAdaptor->new($DB);
my $job = EnsEMBL::Web::Object::BlastTicket->new({
                   'blast_adaptor' => $blast_adaptor,
                   'ticket' => $ticket 
                  });
my $request = $blast_adaptor->job_with_ticket($ticket);
 
warn "REQUEST" . $request;
warn "REQUEST" . $request->ticket;

print "Content-type: text/plain\n\n";
if ($request->status == $blast_adaptor->status_pending()) {
  print EnsEMBL::Web::Component::Blast::render_pending({
                     'pending' => $job->queue_length, 
                     'ticket' => $ticket,
                     'queue_position' => $job->position_in_queue,
                     'running' => $job->running_jobs,
                     'wait_time' => $job->wait_time
        }); 
} elsif ($request->status == $blast_adaptor->status_running()) {
  print EnsEMBL::Web::Component::Blast::render_running({
                     'pending' => $job->queue_length, 
                     'ticket' => $ticket,
                     'queue_position' => $job->position_in_queue,
                     'running' => $job->running_jobs,
                     'wait_time' => $job->wait_time
        }); 
} elsif ($request->status == $blast_adaptor->status_complete()) {
  print EnsEMBL::Web::Component::Blast::render_complete({
                     'pending' => $job->queue_length, 
                     'ticket' => $ticket,
                     'queue_position' => $job->position_in_queue,
                     'running' => $job->running_jobs,
                     'wait_time' => $job->wait_time
        }); 
}

1;
