#!/usr/local/bin/perl

package bookmark;

use CGI;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::RegObj;

my $cgi = CGI->new;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor; 

my $class = "user";
if ($cgi->param('class')) {
  $class = $cgi->param('class');
}

my $table = $class . "_record";

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new(( 
                                                       handle => $db,
                                                       table  => $table 
                                                    )) );

$data->add_field({'Field' => 'name', 'Type' => 'varchar(255)'});
$data->add_field({'Field' => 'description', 'Type' => 'text'});
$data->add_field({'Field' => 'url', 'Type' => 'text'});
$data->add_field({'Field' => 'click', 'Type' => 'int'});
$data->add_field({'Field' => 'created_at', 'Type' => 'timestamp'});
$data->add_field({'Field' => 'modified_at', 'Type' => 'timestamp'});
if ($cgi->param('id')) {
  $data->populate($cgi->param('id'));
  $page->title('Edit bookmark');
  $page->action('edit');
  $page->on_complete('/common/accountview');
} else {
  $page->title('Add bookmark');
  $page->action('create');
  if (!$cgi->param('forward')) {
    $page->on_complete($cgi->param('url'));
  } else {
    $page->on_complete('/common/accountview');
    $page->add_configuration_element('forward', $cgi->param('forward')); 
  }
}

$page->data_definition($data);
$page->on_error('/account/bookmark_error.html');
$page->send_params({ forward => 'yes'});

$page->cancel('yes');

$form = EnsEMBL::Web::Interface::FormDefinition->new();
$form->add_value({ name => $cgi->param('name') });
$form->add_value({ url => $cgi->param('url') });

$page->add_configuration_element('record', 'yes');
$page->add_configuration_element('type', 'bookmark'); 
$page->add_configuration_element('click', '1'); 
$page->add_form_element('name', "Bookmark name", $form);
$page->add_form_element('description', "Short description", $form);
$page->add_form_element('url', "The URL of your bookmark", $form);

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
