#!/usr/local/bin/perl

package dataview;

use CGI;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;

my $cgi = CGI->new;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $EnsEMBL::Web::Apache::Handlers::ENSEMBL_USER_DB_HANDLE; 
$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new(( 
                                                       handle => $db,
                                                       table  => 'record'
                                                    )) );

$data->add_field({'Field' => 'name', 'Type' => 'varchar(255)'});
$data->add_field({'Field' => 'url', 'Type' => 'text'});
$data->add_field({'Field' => 'click', 'Type' => 'int'});
$data->add_field({'Field' => 'created_at', 'Type' => 'timestamp'});
$data->add_field({'Field' => 'modified_at', 'Type' => 'timestamp'});
$data->id($cgi->param('id'));
$data->populate;

$page->data_definition($data);
$page->title('Edit bookmark');
$page->action('edit');
$page->on_complete('/common/accountview');
$page->on_error('/account/bookmark_error.html');

$page->add_text('Describe bookmark here'); 

# User id is added automatically if a user is logged in.
$page->add_configuration_element('record', 'yes');
$page->add_configuration_element('type', 'bookmark'); 
$page->add_configuration_element('click'); 
$page->add_form_element('name', "Bookmark name");
$page->add_form_element('url', "The URL of your bookmark");

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
