#! /usr/local/bin/perl

use strict;
use warnings;

use CGI;

my $cgi = new CGI;

print "Content-type: text/html\n\n";
print "<html>\n";
print "<head><title>Commander example</title></head>\n";
print "<body>\n";
print "<h1>Final destination</h1>\n";
print "<hr noshade>\n";
print "You submitted the following:\n";
print "<ul>\n";
foreach my $key (keys %{ $cgi->Vars }) {
  print "<li>$key: " . $cgi->Vars->{$key} . "</li>\n";
}
print "</ul>\n";
print "<a href='/common/commander'>&larr; Start again</a>\n";
print "</body>\n";
print "</html>\n";
