#!/usr/local/bin/perl

package dataview;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::Apache::Handlers;
use EnsEMBL::Web::DBSQL::Relationship::HasMany;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table    => 'webgroup'
                                                    )) );

my $relationship = EnsEMBL::Web::DBSQL::Relationship::HasMany->new(( 
                                       table => 'webgroup',
                                       has_many => 'users', 
                                       linked_by => 'group_member'
                                       ));

$data->add_relationship($relationship);
$data->discover;

$page->data_definition($data);
$page->title('Create new group');
$page->cancel('yes');
$page->action('create');
$page->on_complete('/common/accountview');
$page->on_error('/dataview/error.html');

$page->add_text('You can create a new group of users here. You will automatically be added to your new group.');

$page->add_configuration_element('level', 'administrator');
$page->add_form_element('name', "Your group name");
$page->add_form_element('blurb', "A description of your group");

$page->add_form_element('type', "Type", EnsEMBL::Web::Interface::FormDefinition->new((
                                        labels => [ { "open" => "Open group" }, 
                                                    { "restricted" => "Restricted group" },
                                                    { "private" => "Private group" },
                                                  ]
                       )));

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
