#! /usr/bin/perl

package sortable;

use strict;
use warnings;

use EnsEMBL::Web::User::Record;
use EnsEMBL::Web::Object::User;
use CGI;


my $cgi = new CGI;
my $url = $cgi->param('url');
warn "------------> redirect: " . $url;
 
if ($ENV{'ENSEMBL_USER_ID'}) {

  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $found = 0;
  my $record = undef;
  foreach my $this ($user->current_config_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::User::Record->new(( type => 'current_config', user => $user->id));
  }
  if ($cgi->param('id')) {
    $record->config($cgi->param('id'));
    $record->save;
  }

}

CGI::redirect($url);

1;
