#! /usr/bin/perl

package sortable;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::RegObj;
use CGI;

my $cgi = new CGI;
my $url = $cgi->param('url');
my $user = $ENSEMBL_WEB_REGISTRY->get_user; 

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this ($user->current_config_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdapator, type => 'current_config', user => $user->id));
  }
  if ($cgi->param('id')) {
    $record->config($cgi->param('id'));
    $record->save;
  }

}

CGI::redirect($url);

1;
