#!/usr/local/bin/perl

package dataview;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $adaptor = EnsEMBL::Web::DBSQL::ViewAdaptor->new();

$adaptor->hostname('ecs3');
$adaptor->port(3307);
$adaptor->database('ensembl_web_user_db');
$adaptor->username('ensro');
$adaptor->password('');
$adaptor->table('webgroup');
$adaptor->discover;

$data->adaptor($adaptor);
$data->discover;

$page->data_definition($data);
$page->title('Create new group');
$page->action('create');
$page->on_complete('http://ensarc-1-14.internal.sanger.ac.uk:6700/dataview/created.html');

$page->add_text('You can create a new group of users here. You will automatically be added to your new group.');

$page->add_form_element('name', "Your group name");
$page->add_form_element('blurb', "A description of your group");
$page->add_form_element('type', "Type");

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
