#! /usr/bin/perl

package remove_group;

use strict;
use warnings;

use EnsEMBL::Web::Record::Group;
use CGI;
my $cgi = new CGI;
my $url = "/common/groupview";
my $user = $ENSEMBL_WEB_REGISTRY->get_user;
if ($user) {
  my $group = EnsEMBL::Web::Object::Group->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdapator,  id => $cgi->param('group_id') )); 
  $url = "/common/groupview?id=" . $group->id;
  if ($cgi->param('user_id') eq $user->id) {
    if ($user->is_administrator($group)) {
      foreach my $record ($group->find_group_records_by_group_record_id($cgi->param('invite_id') )) {
        if ($record->id eq $cgi->param('invite_id')) {
          $record->delete;
        }
      }

    } else {
      $url = "/failed.html";
    }
  }
}

CGI::redirect($url);

1;
