#! /usr/bin/perl

package drawer;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::RegObj;
use CGI;

my $cgi = new CGI;
my $user = $ENSEMBL_WEB_REGISTRY->get_user; 

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this ($user->drawer_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, type => 'drawer', user => $user->id));
  }

  $record->group($cgi->param('group'));
  $record->save;

}

print "Content-type: text/plain\n\n";
print "Done";

1;
