#!/usr/local/bin/perl

package dataview;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::DBSQL::Relationship::HasMany;

use CGI;

my $cgi = new CGI;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $EnsEMBL::Web::Apache::Handlers::ENSEMBL_USER_DB_HANDLE;

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table    => 'webgroup'
                                                    )) );

my $relationship = EnsEMBL::Web::DBSQL::Relationship::HasMany->new(( 
                                       table => 'webgroup',
                                       has_many => 'users', 
                                       linked_by => 'group_member'
                                       ));

$data->add_relationship($relationship);
$data->discover;
$data->populate($cgi->param('id'));

$page->data_definition($data);
$page->title('Edit this group');
$page->action('edit');
$page->cancel('yes');
$page->on_complete('/common/groupview?id=' . $cgi->param('id'));
$page->on_error('/error.html');

$page->add_text('You can edit your group details here.');

$page->add_configuration_element('level', 'administrator');
$page->add_form_element('name', "Your group name");
$page->add_form_element('blurb', "A description of your group");

$page->add_form_element('type', "Type", EnsEMBL::Web::Interface::FormDefinition->new((
                                        labels => [ { "open" => "Open group" }, 
                                                    { "restricted" => "Restricted group" },
                                                    { "private" => "Private group" },
                                                  ]
                       )));

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
