#!/usr/local/bin/perl

### Simple DataView interface for adding

package filter_news;

use CGI;

use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::DBSQL::Relationship::HasMany;

my $cgi = CGI->new;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $sd = EnsEMBL::Web::SpeciesDefs->new();

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new(( 
                                                       hostname => $sd->ENSEMBL_USERDB_HOST,
                                                       port     => $sd->ENSEMBL_USERDB_PORT,
                                                       database => $sd->ENSEMBL_USERDB_NAME,
                                                       username => $sd->ENSEMBL_USERDB_USER,
                                                       password => $sd->ENSEMBL_USERDB_PASS,
                                                       table    => 'record'
                                                    )) );

my ($topic_types, $sp_types);
my $topic_options = EnsEMBL::Web::Interface::FormDefinition->new();
my $sp_options = EnsEMBL::Web::Interface::FormDefinition->new();

my @species = @{$sd->ENSEMBL_SPECIES};
my $sp_values = join(',', @species);

$page->data_definition($data);
$page->title('Select a news filter');
if (my $id = $cgi->param('id')) {
  $page->action('edit');
  $data->populate($id);
  $topic_types = 'enum(none,data,code,schema,feature)';
  $sp_types = "enum('none',$sp_values)";
  $topic_options->add_label({'none' => 'None (show all topics)'});
  $sp_options->add_label({'none' => 'None (show all species)'});
}
else {
  $page->action('create');
  $topic_types = 'enum(data,code,schema,feature)';
  $sp_types = "enum($sp_values)";
}
$page->on_complete('/common/accountview');
$page->on_error('/common/accountview');

$data->add_field({'Field' => 'topic', 'Type' => $topic_types});
$data->add_field({'Field' => 'species', 'Type' => $sp_types});
$data->add_field({'Field' => 'created_at', 'Type' => 'timestamp'});
$data->add_field({'Field' => 'modified_at', 'Type' => 'timestamp'});

## Add standard options
$topic_options->add_label({'data'    => 'Data updates'});
$topic_options->add_label({'code'    => 'API changes'});
$topic_options->add_label({'schema'  => 'Schema changes'});
$topic_options->add_label({'feature' => 'Web features'});

foreach my $species (@species) {
  (my $pretty_sp = $species) =~ s/_/ /;
  $sp_options->add_label({$species=>$pretty_sp});
}

## User id is added automatically if a user is logged in.
$page->add_configuration_element('record', 'yes');
$page->add_configuration_element('type', 'news'); 
$page->add_form_element('topic', "Topic to filter on", $topic_options);
$page->add_form_element('species', "Species to filter on", $sp_options);

EnsEMBL::Web::Document::DataView::simple('User', $page, {
                              'context' => ['context_menu', 'user_menu'],
                              'access' => {'login'=>1}
                              });


1;
