#! /usr/bin/perl

package forgotten;

use strict;
use warnings;

use CGI;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::SpeciesDefs;

my $cgi = new CGI;
my $url = "/login.html?url=/index.html";

if ($cgi->param('email')) {
  my $user = EnsEMBL::Web::Object::User->new({ email => $cgi->param('email') });
  if ($user->id) {
    $url = "/updated_password.html?url=/index.html";
    $user->salt($user->random_string(8));
    $user->save;
    $user->send_reactivation_email;
  } else {
    $url = "/forgotten_no_user.html?url=/index.html";
  }
}

CGI::redirect($url);

1;
