#! /usr/bin/perl

package forgotten;

use strict;
use warnings;

use CGI;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::SpeciesDefs;

my $cgi = new CGI;
my $url = "/login.html?url=/index.html";

my $sd = EnsEMBL::Web::SpeciesDefs->new();
my $site_info = {};
my $sitetype = $sd->ENSEMBL_SITETYPE;
my $sitename = $sitetype eq 'EnsEMBL' ? 'Ensembl' : $sitetype;
$site_info->{'name'} = $sitename;
$site_info->{'base_url'}    = $sd->ENSEMBL_BASE_URL;
$site_info->{'mail_server'} = $sd->ENSEMBL_MAIL_SERVER;
$site_info->{'help_email'}  = $sd->ENSEMBL_HELPDESK_EMAIL;

if ($cgi->param('email')) {
  my $user = EnsEMBL::Web::Object::User->new({ email => $cgi->param('email') });
  if ($user->id) {
    $url = "/updated_password.html?url=/index.html";
    $user->salt(&random_string(8));
    $user->save;
    $user->send_reactivation_email($site_info);
  } else {
    $url = "/forgotten_no_user.html?url=/index.html";
  }
}

CGI::redirect($url);

sub random_string {
  my $length = shift || 8;

  my @chars = ('a'..'z','A'..'Z','0'..'9','_');
  my $random_string;
  foreach (1..$length)
  {
    $random_string .= $chars[rand @chars];
  }
  return $random_string;
}



1;
