#!/usr/local/bin/perl

package dataview;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::RegObj;
use EnsEMBL::Web::DBSQL::Relationship::HasMany;

use CGI;

my $cgi = new CGI;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table    => 'webgroup'
                                                    )) );

my $relationship = EnsEMBL::Web::DBSQL::Relationship::HasMany->new(( 
                                       table => 'webgroup',
                                       has_many => 'users', 
                                       linked_by => 'group_member'
                                       ));

$data->add_relationship($relationship);
$data->discover;
$data->populate($cgi->param('id'));

$page->data_definition($data);
$page->title($page->value_for_form_element('name'));
$page->action('edit');

$page->add_display_element('blurb', "Description");
$page->add_display_element('type', "Type");

$page->footer('<a href="/common/accountview">&larr; Back to account</a>');

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
