#!/usr/local/bin/perl

package groupview;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'groupview',
  'objecttype' => 'User',
  'access'     => {'group' => ''}, ## page only accessible to group members
);

if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'groupview', 'context_menu', 'user_menu' );
  }
  $webpage->action({'login' => 1}); ## page only accessible to logged-in users
}

1;
