#!/usr/local/bin/perl

package help;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

## Search
$controller->add_connections({qw(
  search     EnsEMBL::Web::Controller::Command::Help::Search
  results    EnsEMBL::Web::Controller::Command::Help::Results
)});
## Contact help desk
$controller->add_connections({qw(
  contact    EnsEMBL::Web::Controller::Command::Help::Contact
  send_email EnsEMBL::Web::Controller::Command::Help::SendEmail
)});

$controller->dispatch($ENV{REQUEST_URI});

}

1;
