#!/usr/local/bin/perl

package help;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

## Search
$controller->add_connections({qw(
  Search     EnsEMBL::Web::Controller::Command::Help::Search
  DoSearch   EnsEMBL::Web::Controller::Command::Help::DoSearch
  Results    EnsEMBL::Web::Controller::Command::Help::Results
)});

## Topics
$controller->add_connections({ 
  'Component' => 'EnsEMBL::Web::Controller::Command::Help::Component',
  'Faq'       => 'EnsEMBL::Web::Controller::Command::Help::Faq',
  'Glossary'  => 'EnsEMBL::Web::Controller::Command::Help::Glossary',
  'Movie'     => 'EnsEMBL::Web::Controller::Command::Help::Movie',
  'Feedback'  => 'EnsEMBL::Web::Controller::Command::Help::Feedback',
});

## Contact
$controller->add_connections({qw(
  Contact    EnsEMBL::Web::Controller::Command::Help::Contact
  SendEmail  EnsEMBL::Web::Controller::Command::Help::SendEmail
  EmailSent  EnsEMBL::Web::Controller::Command::Help::EmailSent
)});

## Miscellaneous
$controller->add_connections({qw(
  ArchiveList   EnsEMBL::Web::Controller::Command::Help::ArchiveList
  Permalink     EnsEMBL::Web::Controller::Command::Help::Permalink
)});


$controller->dispatch($ENV{REQUEST_URI});

}

1;
