#!/usr/local/bin/perl

package help;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

## Search
$controller->add_connections({ 
  'Search' => 'EnsEMBL::Web::Controller::Command::Help::Search',
  'DoSearch' => 'EnsEMBL::Web::Controller::Command::Help::DoSearch',
  'Results' => 'EnsEMBL::Web::Controller::Command::Help::Results',
});

## Topics
$controller->add_connections({ 
  'Faq'       => 'EnsEMBL::Web::Controller::Command::Help::Faq',
  'Glossary'  => 'EnsEMBL::Web::Controller::Command::Help::Glossary',
  'Feedback'  => 'EnsEMBL::Web::Controller::Command::Help::Feedback',
});

## Contact
$controller->add_connections({ 
  'Contact' => 'EnsEMBL::Web::Controller::Command::Help::Contact',
  'SendEmail' => 'EnsEMBL::Web::Controller::Command::Help::SendEmail',
  'EmailSent' => 'EnsEMBL::Web::Controller::Command::Help::EmailSent',
});

$controller->dispatch($ENV{REQUEST_URI});

}

1;
