#! /usr/local/bin/perl

package hide_info;

use CGI;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Object::Data::User;
use EnsEMBL::Web::Object::Data::Infobox;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $registry_user = $ENSEMBL_WEB_REGISTRY->get_user;
my $user = EnsEMBL::Web::Object::Data::User->new({ id => $registry_user->id });

my $box = EnsEMBL::Web::Object::Data::Infobox->new();

$box->user_id($user->id);
$box->name($cgi->param('id'));
$box->save;

print "Content-type: text/plain\n\n";
print "Done:";

1;
