#! /usr/bin/perl

package invite;

use EnsEMBL::Web::Record::Group;
use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::Tools::RandomString;
use EnsEMBL::Web::Group::Record;
use EnsEMBL::Web::RegObj;
use EnsEMBL::Web::Object::Data::User;
use EnsEMBL::Web::Object::Data::Group;
use EnsEMBL::Web::Object::Data::Invite;
use EnsEMBL::Web::Mailer::User;

use CGI;
my $cgi = new CGI;

my $url = "/common/user/account";
my $reg_user = $ENSEMBL_WEB_REGISTRY->get_user;
my $user = EnsEMBL::Web::Object::Data::User->new({ id => $reg_user->id });
if ($user) {
  my $group = EnsEMBL::Web::Object::Data::Group->new({ id => $cgi->param('group_id') });
  $url = "/common/groupview?id=" . $group->id;
  if ($cgi->param('user_id') eq $user->id) {
    if ($user->is_administrator_of($group)) {
      my @invites = split(/,/, $cgi->param('invite_email')); 
      foreach my $email (@invites) {
        $email =~ s/ //g;
	&process_invite($user, $group, $email);
      }
      my $feedback = "Invitation email sent to: " . $cgi->param('invite_email');
      $url .= "&feedback=" . CGI::escape($feedback); 
    } else {
      $url = "/failed.html";
    }
  }
}

sub process_invite {
  my ($user, $group, $email) = @_;
  $invite = EnsEMBL::Web::Object::Data::Invite->new;
  $invite->group_id($group->id);
  $invite->email($email);
  $invite->status("pending");
  $invite->code(EnsEMBL::Web::Tools::RandomString::random_string());
  $invite->save;
  my $mailer = EnsEMBL::Web::Mailer::User->new;
  $mailer->send_invite_email($user, $group, $invite, $email);
}

CGI::redirect($url);

1;
