#! /usr/bin/perl

package invite;

use EnsEMBL::Web::Group::Record;
use CGI;
my $cgi = new CGI;

my $url = "/common/accountview";
if ($ENV{'ENSEMBL_USER_ID'}) {
  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $group = EnsEMBL::Web::Object::Group->new(( id => $cgi->param('group_id') )); 
  $url = "/common/groupview?id=" . $group->id;
  if ($cgi->param('user_id') eq $user->id) {
    if ($user->is_administrator($group)) {

      $record = EnsEMBL::Web::Group::Record->new((  user => $group->id, 
                                                    type => "invite" ));
      $record->email($cgi->param('invite_email'));
      $record->status("pending");
      $record->code(random_string());
      $record->save;

      $user->send_invite_email($group, $record, $cgi->param('invite_email'));
      my $feedback = "Invitation email send to: " . $cgi->param('invite_email');
      $url .= "&feedback=" . CGI::escape($feedback); 
    } else {
      $url = "/failed.html";
    }
  }
}

CGI::redirect($url);

sub random_string {
  my $length = shift || 8;

  my @chars = ('a'..'z','A'..'Z','0'..'9','_');
  my $random_string;
  foreach (1..$length)
  {
    $random_string .= $chars[rand @chars];
  }
  return $random_string;
}


1;
