#! /usr/bin/perl

package join_by_invite;

use strict;
use warnings;

use CGI;
use EnsEMBL::Web::Group::Record;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::Object::Group;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::Apache::Handlers;

my $cgi = new CGI;

my $record_id = $cgi->param('record_id');
warn "RECORD ID: " . $record_id;
my @records = EnsEMBL::Web::Group::Record->find_invite_by_group_record_id($record_id);
my $record = $records[0];
my $email = $record->email;
my $group_id = $record->group;

my $user = EnsEMBL::Web::Object::User->new({ email => $email });

if (!$user->id) {

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $form = EnsEMBL::Web::Interface::FormDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;
$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

$data->discover;
$page->data_definition($data);
$page->title('Register for Ensembl');
$page->action('create');
$page->send_params({ id => 'yes', group_id => 'yes' });
$page->on_complete('/common/activate');
$page->on_error('/register/error.html');

$form->add_value({'email' => $email });

$page->add_text('You have been invited to join an Ensembl group. In order to do so, you first need to create a new Ensembl account.');
$page->add_configuration_element('salt', random_string(8));
$page->add_configuration_element('group_id', $group_id);
$page->add_configuration_element('record_id', $record_id);
$page->add_form_element('name', "Your name");
$page->add_form_element('email', "Your email address. You'll use this to log in to Ensembl", $form);
$page->add_form_element('organisation', "Organisation");

EnsEMBL::Web::Document::DataView::simple('User', $page);

} else {
  my $group = EnsEMBL::Web::Object::Group->new(( id => $group_id ));
  warn "WORKING WITH USER: " . $user->id . ": " . $user->email;
  $user->add_group($group);
  $user->save;
  $record->status('accepted');
  $record->save;

  my $url = "/common/accountview";
  print "Location: " . $url;
}

sub random_string {
  my $length = shift || 8;

  my @chars = ('a'..'z','A'..'Z','0'..'9','_');
  my $random_string;
  foreach (1..$length)
  {
    $random_string .= $chars[rand @chars];
  }
  return $random_string;
}


1;
