#!/usr/local/bin/perl

package dataview;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::DBSQL::Relationship::HasMany;
use EnsEMBL::Web::SpeciesDefs;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $species_defs = EnsEMBl::Web::SpeciesDefs->new();

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new(( 
                                                       hostname => $species_defs->{'ENSEMBL_WEB_USER_DB'},
                                                       port     => $species_defs->{''},
                                                       database => $database,
                                                       username => $username,
                                                       password => $password,
                                                       table    => 'webgroup'
                                                    )) );

my $relationship = EnsEMBL::Web::DBSQL::Relationship::HasMany->new(( 
                                       table => 'webgroup',
                                       has_many => 'users', 
                                       linked_by => 'group_member'
                                       ));

$data->add_relationship($relationship);
$data->discover;

$page->data_definition($data);
$page->title('Create new group');
$page->action('create');
$page->on_complete('http://ensarc-1-14.internal.sanger.ac.uk:6700/dataview/created.html');
$page->on_error('http://ensarc-1-14.internal.sanger.ac.uk:6700/dataview/error.html');

$page->add_text('You can create a new group of users here. You will automatically be added to your new group.');

$page->add_configuration_element('level', 'administrator');
$page->add_form_element('name', "Your group name");
$page->add_form_element('blurb', "A description of your group");

$page->add_form_element('type', "Type", EnsEMBL::Web::Interface::FormDefinition->new((
                                        labels => [ { "open" => "Open group" }, 
                                                    { "restricted" => "Restricted group" },
                                                    { "private" => "Private group" },
                                                  ]
                       )));

EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
