#! /usr/bin/perl

package load_config;

use strict;
use warnings;

use EnsEMBL::Web::RegObj;
use EnsEMBL::Web::Object::Data::User;
use Apache2::RequestUtil;

use CGI;
my $cgi = new CGI;
my $script_name = "contigview";


my $url = $cgi->param('url');
my ($host, $params) = split(/\?/, $url);
my (@parameters) = split(/&/, $params); 
my $new_params = "";
foreach my $p (@parameters) {
  if ($p !~ /bottom/) {
    $new_params .= "&" . $p;
  }
}

$new_params =~ s/^&/\?/;
$url = $host . $new_params;

my $session = $ENSEMBL_WEB_REGISTRY->get_session;
$session->set_input($cgi);
my $user = $ENSEMBL_WEB_REGISTRY->get_user;
my $data_user = EnsEMBL::Web::Object::Data::User->new({ id => $user->id }); 

if ($user) {
    warn "PROCESSING CONFIG";
    foreach my $configuration (@{ $data_user->configurations }) {
      warn "CONFIG: " . $configuration->id;
      if ($configuration->id eq $cgi->param('id')) {
        my $string = $configuration->scriptconfig;

        my $r = Apache2::RequestUtil->request();
        $session->create_session_id($r);
        $session->set_script_config_from_string($script_name, $string);
      } 
    }
} else {
  $url = '/error/config_failed.html';
}

CGI::redirect('/common/current_config?url=' . CGI::escape($url) . '&id=' . $cgi->param('id') );

1;
