#! /usr/bin/perl

package login;

use EnsEMBL::Web::Object::User;
use CGI;
my $cgi = new CGI;
my $user = EnsEMBL::Web::Object::User->new({ 
                                      username => $cgi->param('username'),
                                      password => $cgi->param('password')
                                           });

my $url = "/failed.html";
if ($user->name) {
  warn "OK: Logging in as " . $user->name;
  my $encrypted = EnsEMBL::Web::DBSQL::UserDB::encryptID($user->id);
  my $cookie = CGI::Cookie->new(
     -name    => EnsEMBL::Web::SpeciesDefs->ENSEMBL_USER_COOKIE,
     -value   => $encrypted,
     -domain  => EnsEMBL::Web::SpeciesDefs->ENSEMBL_COOKIEHOST,
     -path    => "/",
     -expires => "Monday, 31-Dec-2010 23:59:59 GMT"
  );
  print "Set-cookie: $cookie";
  $url = $cgi->param('url');
}

print "Location: $url";

1;

