#!/usr/local/bin/perl

package manage_members;

use EnsEMBL::Web::Document::WebPage;
#EnsEMBL::Web::Document::WebPage::simple( 'User', {'webgroup_id'=>'', 'level'=>'administrator'} );
EnsEMBL::Web::Document::WebPage::simple( 'User' );
1;
