#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::DBSQL::UserDB;
use EnsEMBL::Web::User::Record;

warn("AJAX: Updating bookmark"); 

my $T = new CGI;
my $bookmark = $T->param('bookmark');
my $user = $T->param('user');
my $name = $T->param('name');
my $action = $T->param('action');
my $user_id = $ENV{'ENSEMBL_USER_ID'};

print "Content-type: text/plain\n\n";

if ($user eq $user_id) {
  my $user_adaptor = EnsEMBL::Web::DBSQL::UserDB->new();
  if ($action eq 'update') {
    my @records = EnsEMBL::Web::User::Record->find_bookmark_by_id($bookmark);
    my $record = $records[0];
    $record->adaptor($user_adaptor);
    $record->name($name);
    $record->save;
    print $name;
  } elsif ($action eq 'delete') {
    my @records = EnsEMBL::Web::User::Record->find_bookmark_by_id($bookmark);
    my $record = $records[0];
    $record->adaptor($user_adaptor);
    $record->delete;
  }
} else {
  print "No access";
}

1;
