#! /usr/bin/perl

package mixer;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::Object::User;
use CGI;


my $cgi = new CGI;
 
if ($ENV{'ENSEMBL_USER_ID'}) {

  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $found = 0;
  my $record = undef;
  foreach my $this ($user->mixer_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( type => 'mixer', user => $user->id));
  }

  $record->settings($cgi->param('settings'));
  $record->save;

}

print "Content-type: text/plain\n\n";
print "Done";

1;
