#! /usr/bin/perl

package mixer;

use strict;
use warnings;

use EnsEMBL::Web::Data::Mixer;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user; 

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this (@{ $user->mixers }) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Data::Mixer->new;
    $record->user_id($user->id);
  }

  $record->settings($cgi->param('settings'));
  $record->save;
}

print "Content-type: text/plain\n\n";
print "Done";

1;
