#! /usr/bin/perl

package mixer;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user; 

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this ($user->mixer_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( type => 'mixer', user => $user->id, adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor));
  }

  $record->settings($cgi->param('settings'));
  $record->save;

}

print "Content-type: text/plain\n\n";
print "Done";

1;
