#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::RegObj;

my $T = new CGI;
my $id = $T->param('id');
my $url = $T->param('url');

$url =~ s/\\\?/\?/g;
$url =~ s/!and!/&/g;
$url =~ s/!with!/;/g;

my $adaptor = $ENSEMBL_WEB_REGISTRY->userAdaptor;
my @records = EnsEMBL::Web::Record::User->find_bookmark_by_id($id, { adaptor => $adaptor });
my $record = $records[0];

my $click = $record->click;
if ($click) {
  $record->click($click + 1)
} else {
  $record->click(1);
}
$record->adaptor($adaptor);
$record->save;

CGI::redirect($url);

1;
