#!/usr/local/bin/perl

use strict;
use warnings;

package register;

use CGI;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::SpeciesDefs;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;

my $sd = EnsEMBL::Web::SpeciesDefs->new();
my $help_email = $sd->ENSEMBL_HELPDESK_EMAIL;
my $sitetype = $sd->ENSEMBL_SITETYPE;
my $sitename = $sitetype eq 'EnsEMBL' ? 'Ensembl' : $sitetype;

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

$data->discover;
$page->data_definition($data);
$page->title('Register for '.$sitename);
$page->footer(qq(Need help? <a href="mailto:$help_email">Contact the helpdesk</a> &middot; <a href="/info/about/privacy.html">Privacy policy</a>'));
$page->action('create');
$page->send_params({ id => 'yes'});
$page->on_complete('/common/activate');
$page->on_error('/register/error.html');

$page->add_configuration_element('salt', EnsEMBL::Web::Object::User::random_string(8));
$page->add_form_element('name', "Your name");
$page->add_form_element('email', "Your email address.<br />You'll use this to log in to $sitename");
$page->add_form_element('organisation', "Organisation");

if ($cgi->param('email')) {
  my $user = EnsEMBL::Web::Object::User->new({ email => $cgi->param('email') });
  if ($user->id) {
    my $url = "/error/email.html";
    CGI::redirect($url);
  } else {
    EnsEMBL::Web::Document::DataView::simple('User', $page);
  }
} else {
  EnsEMBL::Web::Document::DataView::simple('User', $page);
}

1;
