#! /usr/bin/perl

package remove_record;

use CGI;
use EnsEMBL::Web::Object::Data::User;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $url = "/index.html";
my $registry_user = $ENSEMBL_WEB_REGISTRY->get_user;
my $user = EnsEMBL::Web::Object::Data::User->new({ id => $registry_user->id });

if ($user) {
  $url = "/common/user/account";
  if ($cgi->param('url')) {
    $url = $cgi->param('url');
  }

  foreach my $record (@ { $user->records }) {
    if ($record->id eq $cgi->param('id')) {
     $record->destroy;
    }
  }
}

CGI::redirect($url);

1;
