#! /usr/bin/perl

package remove_group;

use CGI;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $url = "/common/accountview";
my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {
  my $group = EnsEMBL::Web::Object::Group->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, id => $cgi->param('group_id') )); 
  if ($user->is_administrator($group)) {
    $group->status('inactive');
    $group->save;
  } else {
    $url = "/failed.html";
  }
}

CGI::redirect($url);

1;
