#! /usr/bin/perl

package remove_record;

use CGI;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $url = "/index.html";
my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {
  $url = "/common/accountview";
  if ($cgi->param('url')) {
    $url = $cgi->param('url');
  }

  $user->load;
  foreach my $record (@ { $user->records }) {
    if ($record->id eq $cgi->param('id')) {
     $record->delete;
    }
  }
}

CGI::redirect($url);

1;
