#! /usr/bin/perl

package remove_group;

use strict;
use warnings;

use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::Object::Group;

use CGI;
my $cgi = new CGI;
my $url = "/common/user/account";
my $user = $ENSEMBL_WEB_REGISTRY->get_user;
if ($user) {
  
  my $remove_user = EnsEMBL::Web::Object::User->new({ adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, id => $cgi->param('user_id') });
  my $group = EnsEMBL::Web::Object::Group->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, id => $cgi->param('group_id') )); 

  if ($user->is_administrator_of($group)) {
    $group->remove_user($remove_user);
    $group->save;
  }
  $url = "/common/groupview?id=" . $group->id;

}

CGI::redirect($url);

1;
