#! /usr/bin/perl

package remove_group;

use CGI;
my $cgi = new CGI;

my $url = "/common/accountview";
if ($ENV{'ENSEMBL_USER_ID'}) {
  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $record = EnsEMBL::Web::User::Record->new(( id => $cgi->param('id') )); 
  $record->delete;
}

print "Location: " . $url;

1;
