#! /usr/bin/perl

package remove_group_record;

use CGI;
use EnsEMBL::Web::RegObj;
use EnsEMBL::Web::Object::Data::User;
use EnsEMBL::Web::Object::Data::Group;
use EnsEMBL::Web::Record::Group;

my $cgi = new CGI;

my $url = "/common/groupview?id=" . $cgi->param('group_id');
if ($ENV{'ENSEMBL_USER_ID'}) {
  my $user = EnsEMBL::Web::Object::Data::User->new({ id => $ENSEMBL_WEB_REGISTRY->get_user->id }); 
  my $group = EnsEMBL::Web::Object::Data::Group->new({ id => $cgi->param('group_id') }); 
  if ($user->is_administrator_of($group)) {
    my $record = EnsEMBL::Web::Record::Group->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, id => $cgi->param('id') )); 
    $record->delete;
  }
}

CGI::redirect($url);

1;
