#! /usr/bin/perl

package remove_group;

use strict;
use warnings;

use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::Object::Group;

use CGI;
my $cgi = new CGI;
my $url = "/common/accountview";
if ($ENV{'ENSEMBL_USER_ID'}) {
  
  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $remove_user = EnsEMBL::Web::Object::User->new({ id => $cgi->param('user_id') });
  my $group = EnsEMBL::Web::Object::Group->new(( id => $cgi->param('group_id') )); 
  if ($user->is_administrator_of($group)) {
    $group->remove_user($remove_user);
    $group->save;
  }
  $url = "/common/groupview?id=" . $group->id;

}

print "Location: " . $url;

1;
