#! /usr/local/bin/perl

package reset_info_boxes;

use CGI;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Object::Data::User;
use EnsEMBL::Web::Object::Data::Infobox;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $registry_user = $ENSEMBL_WEB_REGISTRY->get_user;
my $user = EnsEMBL::Web::Object::Data::User->new({ id => $registry_user->id });

if ($user) {
  foreach my $info_box (@{ $user->infoboxes }) {
    $info_box->destroy;
  }  
}

my $url = "/common/accountview";

CGI::redirect($url);

1;
