#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::Document::HTML::SpeciesList;
use EnsEMBL::Web::RegObj;

my $T = new CGI;
my $favourites= $T->param('favourites');
my $list = $T->param('list');

my $user = $ENSEMBL_WEB_REHISTRY->get_user;

if ($user) {
  my ($record) = $user->species_records;
  if ($record) {
    $record->delete
  }
}

my $url = "/index.html";
CGI::redirect($url);

1;
