#! /usr/local/bin/perl

package reset_info_boxes;

use CGI;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::User::Record;
use EnsEMBL::Web::RegObj;

my $cgi = new CGI;

my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {
  foreach my $info_box ($user->info_records) {
    $info_box->delete;
  }  
}

my $url = "/common/accountview";

CGI::redirect($url);

1;
