#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::Document::HTML::SpeciesList;
use EnsEMBL::Web::RegObj;

my $T = new CGI;
my $favourites= $T->param('favourites');
my $list = $T->param('list');

my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {

  my ($record) = $user->species_records;

  warn "SAVING FAVOURITES for " . $user->id;

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, type => 'species', user => $user->id ));
    warn "CREATING RECORD: " . $record;
  }

  $record->favourites($favourites);
  $record->list($list);

  $record->save;

}

my $html = EnsEMBL::Web::Document::HTML::SpeciesList->render("fragment");
print "Content-type: text/plain\n\n";
print $html;


1;
