#! /usr/local/bin/perl

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::User::Record;
use EnsEMBL::Web::Document::HTML::SpeciesList;

my $T = new CGI;
my $favourites= $T->param('favourites');
my $list = $T->param('list');

my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'}});

my ($record) = $user->species_records;
if (!$record) {
  $record = EnsEMBL::Web::User::Record->new(( type => 'species', user => $user->id ));
}


$record->favourites($favourites);
$record->list($list);

$record->save;

my $html = EnsEMBL::Web::Document::HTML::SpeciesList->render("fragment");
print "Content-type: text/plain\n\n";
print $html;


1;
