#! /usr/bin/perl

package save_config;

use strict;
use warnings;

use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;

use EnsEMBL::Web::RegObj;
use Data::Dumper;
use CGI;

my $cgi = new CGI;
my $url = $cgi->param('url');
my $script_name = "contigview";

my $session = $ENSEMBL_WEB_REGISTRY->get_session;
$session->set_input($cgi);
my $string = $session->get_script_config_as_string($script_name);

my $cgi = CGI->new;
my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();

my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user_record'
                                                    )) );

$data->add_field({'Field' => 'name', 'Type' => 'varchar(255)'});
$data->add_field({'Field' => 'description', 'Type' => 'text'});
$data->add_field({'Field' => 'config', 'Type' => 'text'});
$data->add_field({'Field' => 'scriptconfig', 'Type' => 'text'});
$data->add_field({'Field' => 'url', 'Type' => 'text'});
$data->add_field({'Field' => 'created_at', 'Type' => 'timestamp'});
$data->add_field({'Field' => 'modified_at', 'Type' => 'timestamp'});

$page->action('create');
$page->title('Save configuration');
$page->add_form_element('name', "Configuration name");

if ($cgi->param('id')) {
  $data->populate($cgi->param('id'));
  $page->action('edit');
  $page->title('Update configuration');
  $page->add_text('<b>Your configuration settings have changed.</b> Click "Submit" to save your changes.');
  $page->add_text('Alternatively, you can save this configuration under a different name by <a href="/common/save_config?url=' . $cgi->param('url') . '">clicking here</a>.');
} else {
  $page->add_text('Describe your configuration here, and then click "Submit" to save it. Once saved, you can share your configuration with groups you administer.');
  $page->add_form_element('description', "A brief description of your configuration");
}

$page->data_definition($data);
$page->cancel('yes');
$page->send_params({ id => 'yes' });
$page->on_complete('/common/current_config?url=' . CGI::escape($cgi->param('url')));
$page->on_error('/error/config_failed.html');


# User id is added automatically if a user is logged in.
$page->add_configuration_element('record', 'yes');
$page->add_configuration_element('type', 'configuration');
$page->add_configuration_element('url', $cgi->param('url'));
$page->add_configuration_element('scriptconfig', $string);


EnsEMBL::Web::Document::DataView::simple('User', $page);

1;
