#! /usr/bin/perl

package accept;

use strict;
use warnings;

use CGI;

my $cgi = new CGI;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::Object::User;
use EnsEMBL::Web::RegObj;

my $user_id = $ENV{'ENSEMBL_USER_ID'};
if ($user_id) {

  my $page = EnsEMBL::Web::Interface::PageDefinition->new();
  my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
  my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;
  $data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                      )) );
  $data->discover;
  $data->id($user_id);
  $page->data_definition($data);
  $page->title('Change password');
  $page->action('edit');
  $page->cancel('yes');
  $page->on_complete('/common/accountview?feedback=Your password has been updated');
  $page->on_error('/error/error.html');
  $page->add_form_element('password', "Your new password");

  if ($cgi->param('password')) {
    my $user = EnsEMBL::Web::Object::User->new({ id => $user_id });
    $user->password($user->encrypt($cgi->param('password')));
    $user->save;
    my $url = $page->on_complete;
    print "Location:" . $url;
  } else {
    EnsEMBL::Web::Document::DataView::simple('User', $page);
  }

}

1;
