#! /usr/bin/perl

package sortable;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
my $url = "/common/user/account";
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user; 

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this ($user->sortable_records) {
    $record = $this;
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, type => 'sortable', user => $user->id));
  }
  if ($cgi->param('type') =~ /alpha|group/) {
    $record->kind($cgi->param('type'));
    $record->save;
  }

}

CGI::redirect($url);

1;
