#! /usr/bin/perl

package unsubscribe;

use CGI;
my $cgi = new CGI;

my $url = "/common/accountview";

if ($ENV{'ENSEMBL_USER_ID'}) {
  my $user = EnsEMBL::Web::Object::User->new({ id => $ENV{'ENSEMBL_USER_ID'} });
  my $group = EnsEMBL::Web::Object::Group->new(( id => $cgi->param('id') )); 
  $group->remove_user($user);
  $group->save;
}

CGI::redirect($url);

1;
