#!/usr/local/bin/perl

package update;

use CGI;

my $cgi = new CGI;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;
use EnsEMBL::Web::RegObj;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;

if ($cgi->param('id') eq $ENV{'ENSEMBL_USER_ID'}) {

$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

$data->discover;
$data->populate($cgi->param('id'));
$page->data_definition($data);
$page->title('Update your Ensembl account');
$page->action('edit');
$page->cancel('yes');
$page->on_complete('/common/user/account');
$page->on_error('/account/error.html');

$page->add_form_element('name', "Name");
$page->add_form_element('organisation', "Organisation");

EnsEMBL::Web::Document::DataView::simple('User', $page);

} else {
  my $fail_url = "/error/failed.html";
  CGI::redirect($fail_url);
}


1;
