#! /usr/local/bin/perl

package user_data;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

$controller->add_connections(
  {'Upload'     => 'EnsEMBL::Web::Controller::Command::UserData::Upload' },
  {'Save'       => 'EnsEMBL::Web::Controller::Command::UserData::Save' },
  {'Manage'     => 'EnsEMBL::Web::Controller::Command::UserData::Manage' },
);

$controller->dispatch($ENV{REQUEST_URI});

}

1;
