#! /usr/local/bin/perl

package user_data;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

$controller->add_connections({qw(
  Upload       EnsEMBL::Web::Controller::Command::UserData::Upload
  ShareUpload  EnsEMBL::Web::Controller::Command::UserData::ShareUpload
  SaveUpload   EnsEMBL::Web::Controller::Command::UserData::SaveUpload
  ManageUpload EnsEMBL::Web::Controller::Command::UserData::ManageUpload

  AttachDAS    EnsEMBL::Web::Controller::Command::UserData::AttachDAS
  AttachURL    EnsEMBL::Web::Controller::Command::UserData::AttachURL
  SaveRemote   EnsEMBL::Web::Controller::Command::UserData::SaveRemote
  SaveDAS      EnsEMBL::Web::Controller::Command::UserData::SaveDAS
  SaveURL      EnsEMBL::Web::Controller::Command::UserData::SaveURL
  ManageRemote EnsEMBL::Web::Controller::Command::UserData::ManageRemote
  DeleteDAS    EnsEMBL::Web::Controller::Command::UserData::DeleteDAS
)});

$controller->dispatch($ENV{REQUEST_URI});

}

1;
