#! /usr/local/bin/perl

package user_data;

use strict;
use warnings;

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

$controller->add_connections({qw(
  Summary      EnsEMBL::Web::Controller::Command::UserData::Upload
  Upload       EnsEMBL::Web::Controller::Command::UserData::Upload
  ShareUpload  EnsEMBL::Web::Controller::Command::UserData::ShareUpload
  SaveUpload   EnsEMBL::Web::Controller::Command::UserData::SaveUpload
  ManageUpload EnsEMBL::Web::Controller::Command::UserData::ManageUpload
  DeleteUpload EnsEMBL::Web::Controller::Command::UserData::DeleteUpload
  AttachDAS    EnsEMBL::Web::Controller::Command::UserData::AttachDAS
  AttachURL    EnsEMBL::Web::Controller::Command::UserData::AttachURL
  SaveRemote   EnsEMBL::Web::Controller::Command::UserData::SaveRemote
  ManageRemote EnsEMBL::Web::Controller::Command::UserData::ManageRemote
)});

$controller->dispatch($ENV{REQUEST_URI});

}

1;
