#! /usr/bin/perl

package sortable;

use strict;
use warnings;

use EnsEMBL::Web::Record::User;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {

  my $found = 0;
  my $record = undef;
  foreach my $this ($user->opentab_records) {
    if ($this->name eq $cgi->param('name')) {
      $record = $this;
    }
  }

  if (!$record) {
    $record = EnsEMBL::Web::Record::User->new(( adaptor => $ENSEMBL_WEB_REGISTRY->userAdaptor, type => 'opentab', user => $user->id));
  }

  $record->tab($cgi->param('tab'));
  $record->name($cgi->param('name'));
  $record->save;

}

print "Content-type: text/plain\n\n";
print "Done";

1;
