#! /usr/bin/perl

package user_tabs;

use strict;
use warnings;

use EnsEMBL::Web::Data::User;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {
  my $found = 0;
  
  my ($tab) = grep {$_->name eq $cgi->param('name')}
                $user->opentabs
                  if $cgi->param('name');
  
  $tab ||= EnsEMBL::Web::Data::Record::Opentab::User->new();

  $tab->user_id($user->id);
  $tab->tab($cgi->param('tab'));
  $tab->name($cgi->param('name'));
  $tab->save;
}

print "Content-type: text/plain\n\n";
print "Done";

1;
