#!/usr/local/bin/perl

package register;

use CGI;

my $cgi = new CGI;
use EnsEMBL::Web::Document::DataView;
use EnsEMBL::Web::Interface::PageDefinition;
use EnsEMBL::Web::Interface::FormDefinition;
use EnsEMBL::Web::DBSQL::DataDefinition;
use EnsEMBL::Web::DBSQL::ViewAdaptor;

use EnsEMBL::Web::Apache::Handlers;

my $page = EnsEMBL::Web::Interface::PageDefinition->new();
my $data = EnsEMBL::Web::DBSQL::DataDefinition->new();
my $db = $ENSEMBL_WEB_REGISTRY->dbAdaptor;
$data->adaptor(EnsEMBL::Web::DBSQL::ViewAdaptor->new((
                                                       handle => $db,
                                                       table  => 'user'
                                                    )) );

$data->discover;
$data->populate($cgi->param('id'));
$page->data_definition($data);
$page->title('Log in to your Ensembl account');
$page->action('edit');
$page->send_params({ id => 'yes', password => 'yes' });
$page->on_complete('/common/set_cookie');
$page->on_error('/register/error.html');

$page->add_configuration_element('conditional', 'salt');

$page->add_display_element('name', "User name");
$page->add_display_element('organisation', "Organisation");

$conditional = EnsEMBL::Web::Interface::FormDefinition->new();
$conditional->add_option({ 'conditional' => 1 });

$page->add_form_element('salt', "Your activation code", $conditional);
$page->add_form_element('password', "Your password");

EnsEMBL::Web::Document::DataView::simple('User', $page);


1;
