#! /usr/bin/perl

package user_tabs;

use strict;
use warnings;

use EnsEMBL::Web::Data::Opentab;
use EnsEMBL::Web::Data::User;
use EnsEMBL::Web::RegObj;
use CGI;


my $cgi = new CGI;
 
my $user = $ENSEMBL_WEB_REGISTRY->get_user;

if ($user) {

print STDERR "USER IS HERE";
  my $found = 0;
  my $tab = undef;
  foreach my $open_tab (@{ $user->opentabs }) {
    if ($open_tab->name eq $cgi->param('name')) {
      $tab = $open_tab;
    }
  }

  if (!$tab) {
    $tab = EnsEMBL::Web::Data::Opentab->new();
  }

  $tab->user_id($user->id);
  $tab->tab($cgi->param('tab'));
  $tab->name($cgi->param('name'));
  $tab->save;

} else {
print STDERR "USER IS NOOOT HERE";
}

print "Content-type: text/plain\n\n";
print "Done";

1;
