#!/usr/local/bin/perl

package Workshops_Online;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage= new EnsEMBL::Web::Document::WebPage(
  'renderer'   => 'Apache',
  'outputtype' => 'HTML',
  'scriptname' => 'Workshops_Online',
  'objecttype' => 'Help',
);

if( $webpage->has_a_problem() ) {
  $webpage->render_error_page( $webpage->problem->[0] );
} else {
  foreach my $object( @{$webpage->dataObjects} ) {
    $webpage->configure( $object, 'Workshops_Online', 'tutorial_menu' );
  }
  $webpage->action();
}

1;
