# set the "ensembl alias name" and "ensembl common name" for each species used in Ensembl
# this values are also uploaded in the meta table of each core db and then used by
# the web code for display.
#
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10116,"Rat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10116,"Norway rat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31033,"Fugu","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31033,"torafugu","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7165,"Anopheles","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7165,"African malaria mosquito","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (6239,"C.elegans","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (6239,"nematode","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9031,"Chicken","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9031,"chicken","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (99883,"Tetraodon","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (99883,"Fresh water pufferfish","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9913,"Cow","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9913,"cattle","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8364,"X.tropicalis","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8364,"western clawed frog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (4932,"S.cerevisiae","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (4932,"baker's yeast","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7719,"C.intestinalis","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7719,"Sea squirt Ciona intestinalis","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9606,"Human","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9606,"human","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7227,"Fruitfly","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7227,"fruit fly","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10090,"Mouse","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10090,"house mouse","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7955,"Zebrafish","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7955,"zebrafish","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (51511,"C.savignyi","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (51511,"Sea squirt Ciona savignyi","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (13616,"Opossum","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (13616,"gray short-tailed opossum","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7159,"Aedes","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7159,"yellow fever mosquito","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9544,"Macaque","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9544,"rhesus monkey","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9785,"Elephant","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9785,"African savanna elephant","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9371,"Lesser hedgehog tenrec","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9371,"small Madagascar hedgehog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9986,"Rabbit","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9986,"rabbit","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9361,"Armadillo","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9361,"nine-banded armadillo","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (69293,"Stickleback","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (69293,"three spined stickleback","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8090,"Medaka","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8090,"Japanese medaka","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9598,"Chimpanzee","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9598,"chimpanzee","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9615,"Dog","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9615,"dog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9258,"Platypus","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9258,"platypus","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"Pig","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"pig","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9685,"Cat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9685,"cat","ensembl common name");
# 2X genomes
insert into ncbi_taxa_name (taxon_id, name, name_class) values (42254,"Shrew","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (42254,"European shrew","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30611,"Bushbaby","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30611,"small-eared galago","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59463,"Microbat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59463,"little brown bat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9365,"Hedgehog","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9365,"western European hedgehog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10141,"Guinea Pig","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10141,"domestic guinea pig","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (43179,"Squirrel","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (43179,"thirteen-lined ground squirrel","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (37347,"Tree Shrew","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (37347,"northern tree shrew","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30608,"Mouse Lemur","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30608,"grey mouse lemur","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9978,"Pika","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9978,"American pika","ensembl common name");
