# set the "ensembl alias name" and "ensembl common name" for each species used in Ensembl
# this values are also uploaded in the meta table of each core db and then used by
# the web code for display.
#
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10116,"Rat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10116,"Norway rat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31033,"Fugu","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31033,"torafugu","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7165,"Anopheles","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7165,"African malaria mosquito","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (6239,"C.elegans","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (6239,"nematode","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9031,"Chicken","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9031,"chicken","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (99883,"Tetraodon","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (99883,"Fresh water pufferfish","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9913,"Cow","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9913,"cattle","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8364,"X.tropicalis","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8364,"western clawed frog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (4932,"S.cerevisiae","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (4932,"baker's yeast","ensembl common name"); #'
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7719,"C.intestinalis","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7719,"Sea squirt Ciona intestinalis","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9606,"Human","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9606,"human","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7227,"Fruitfly","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7227,"fruit fly","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10090,"Mouse","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10090,"house mouse","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7955,"Zebrafish","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7955,"zebrafish","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (51511,"C.savignyi","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (51511,"Sea squirt Ciona savignyi","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (13616,"Opossum","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (13616,"gray short-tailed opossum","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7159,"Aedes","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7159,"yellow fever mosquito","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9544,"Macaque","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9544,"rhesus monkey","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9785,"Elephant","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9785,"African savanna elephant","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9371,"Lesser hedgehog tenrec","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9371,"small Madagascar hedgehog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9986,"Rabbit","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9986,"rabbit","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9361,"Armadillo","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9361,"nine-banded armadillo","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (69293,"Stickleback","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (69293,"three spined stickleback","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8090,"Medaka","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8090,"Japanese medaka","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9598,"Chimpanzee","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9598,"chimpanzee","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9615,"Dog","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9615,"dog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9258,"Platypus","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9258,"platypus","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"Pig","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"pig","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9685,"Cat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9685,"cat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9600,"Orangutan","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9600,"orangutan","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9796,"Horse","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9796,"horse","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9593,"Gorilla","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9593,"gorilla","ensembl common name");

# 2X genomes
insert into ncbi_taxa_name (taxon_id, name, name_class) values (42254,"Shrew","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (42254,"European shrew","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30611,"Bushbaby","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30611,"small-eared galago","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59463,"Microbat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59463,"little brown bat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9365,"Hedgehog","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9365,"western European hedgehog","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10141,"Guinea Pig","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10141,"domestic guinea pig","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (43179,"Squirrel","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (43179,"thirteen-lined ground squirrel","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (37347,"Tree Shrew","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (37347,"northern tree shrew","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30608,"Mouse Lemur","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30608,"grey mouse lemur","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9978,"Pika","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9978,"American pika","ensembl common name");

insert into ncbi_taxa_name (taxon_id, name, name_class) values (9739,"Dolphin","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9739,"Bottlenose dolphin","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9478,"Tarsier","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9478,"Philippine tarsier","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10020,"Kangaroo rat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (10020,"Ords kangaroo rat","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30538,"Alpaca","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (30538,"alpaca","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (132908,"Megabat","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (132908,"Large flying fox","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9813,"Hyrax","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9813,"cape rock hyrax","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59729,"Zebra Finch","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (59729,"Zebra Finch","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9358,"Sloth","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9358,"Two-toed sloth","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (28377,"Anole Lizard","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (28377,"Green anole Lizard","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9315,"Wallaby","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9315,"Tammar Wallaby","ensembl common name");

insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"Pig","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9823,"pig","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9483,"Marmoset","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9483,"marmoset","ensembl common name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9557,"Hamadryas baboon","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9557,"hamadryas baboon","ensembl common name");
#insert into ncbi_taxa_name (taxon_id, name, name_class) values (,"","ensembl alias name");
#insert into ncbi_taxa_name (taxon_id, name, name_class) values (,"","ensembl common name");

# Internal nodes for the GeneTrees
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33553,  "Mouse/Rat/Squirrel ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (39107,  "Old World rodents","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (129949, "Smegmamorph fish","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (186625, "Bony fish","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (207598, "Human/Chimp/Gorilla ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (311790, "African mammals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314145, "Carnivore/Insectivore/Ungulate mammalian ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314146, "Primates/Rodents ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (376911, "Wet nose lemurs","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7147,   "Flies","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7157,   "Mosquitos","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7711,   "Chordates","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9347,   "Placental mammals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9362,   "Insectivore mammals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9989,   "81.05","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31031,  "65","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32523,  "Tetrapods","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32524,  "Amniotes","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33554,  "Carnivores","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (40674,  "Mammals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (117571, "Bony vertebrates","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314147, "Rodents and rabbits","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7718,   "Ciona ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9443,   "Primates","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9526,   "Apes and old world monkeys","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9604,   "Human/Chimp/Orang ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9975,   "Rabbit/Pika ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32485,  "Bony fish, not zebrafish","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32525,  "Marsupial/Mammal","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33154,  "Fungi/Metazoa ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33213,  "Bilateral animals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33316,  "Coelomate animals","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (376913, "Human/Chimp/Orang/Macaque/Tarsier ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (91561,  "Cow/Alpaca/Dolphin ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9397,   "Bats","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8825,   "Birds","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32561,  "Reptiles","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9348,   "Sloth/Anteater/Armadillo ancestor","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9263,   "Marsupials","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (91561,"Even-toed ungulates","ensembl alias name");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314293,"Simians","ensembl alias name");
#insert into ncbi_taxa_name (taxon_id, name, name_class) values (,"","ensembl alias name");

# Timetree divergence times for the GeneTree internal nodes
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33553,  "78.91","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (39107,  "36.95","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (129949, "180","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (186625, "320","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (207598, "8.78","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (311790, "93.95","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314145, "87.98","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314146, "106.69","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (376911, "69.22","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7147,   "250","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7157,   "200","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7711,   "550","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9347,   "102.41","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9362,   "67.92","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9989,   "81.05","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (31031,  "65","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32523,  "358.99","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32524,  "325.75","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33554,  "56.34","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (40674,  "183.61","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (117571, "420","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314147, "81.16","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (7718,   "100","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9443,   "82.95","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9526,   "30.96","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9604,   "16.24","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9975,   "48.42","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32485,  "190","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32525,  "165.83","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33154,  "1500","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33213,  "580","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (33316,  "570","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (376913, "56.70","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (91561,  "61.33","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9397,   "60.22","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (8825,   "105.00","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (32561,  "267.03","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9348,   "64.50","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (9263,   "148","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (314293, "45.16","ensembl timetree mya");
insert into ncbi_taxa_name (taxon_id, name, name_class) values (91561,  "65.22","ensembl timetree mya");
#insert into ncbi_taxa_name (taxon_id, name, name_class) values (,"","ensembl timetree mya");
