#!/usr/local/bin/perl

package dumpconfig;
use strict;
use EnsWeb;
use EnsEMBL::Web::Config;

my $config = Config->new( EnsWeb::species_defs );
print &EnsWeb::make_cgi_header( 'initfocus'=>1 ),
      &EnsWeb::print_form();
      $config->display_sitedefs();
      
print &EnsWeb::make_cgi_footer();

1;
