#!/usr/local/bin/perl

=head1 NAME

perl/private/help_preview - print a preview of a help article

=head1 DESCRIPTION

This script prints reads a preview of a help article from a file into a popup
window. See perl/private/helpdb for invocation.

=head1 LICENCE

This code is distributed under an Apache style licence:
Please see http://www.ensembl.org/code_licence.html for details

=head1 AUTHOR

Patrick Meidl <pm2@sanger.ac.uk>

=head1 CONTACT

Post questions to the EnsEMBL development list ensembl-dev@ebi.ac.uk

=cut

use strict;
use warnings;
no warnings 'uninitialized';

$| = 1;

use EnsEMBL::Web::RegObj;

my $HELPVIEW = "/perl/helpview";
my $HELPGFX = "/gfx/helpview";
my $TMPDIR = $ENSEMBL_WEB_REGISTRY->species_defs->ENSEMBL_TMP_DIR;

print qq(Content-type: text/html\n\n);
print <<EOH;
<html>
  <head>
    <title>Ensembl HelpDB Editor - preview</title>
    <link rel="stylesheet" type="text/css" href="/$ENV{'ENSEMBL_SPECIES'}/cssfixerupper">
  </head>
  <body>
EOH

open PREFILE, "<$TMPDIR/help_preview.tmp" or die
    "Could not open $TMPDIR/help_preview.tmp for reading: $!";
while (<PREFILE>) {
    $_ =~ s/HELP_(.*?)_HELP/$HELPVIEW?se=1&kw=$1/mg; 
    $_ =~ s/IMG_(.*?)_IMG/$HELPGFX\/$1/mg;
    print $_ ;
}
close PREFILE;

print qq(</body></html>);

