#!/bin/sh
#LICENSE
#
#  Copyright (c) 1999-2013 The European Bioinformatics Institute and
#  Genome Research Limited.  All rights reserved.
#
#  This software is distributed under a modified Apache license.
#  For license details, please see
#
#    http://www.ensembl.org/info/about/code_licence.html
#
#CONTACT
#
#  Please email comments or questions to the public Ensembl
#  developers list at <dev@ensembl.org>.
#
#  Questions may also be sent to the Ensembl help desk at
#  <helpdesk@ensembl.org>.
#
# DESCRIPTION:
# This file calls view_alignment.pl. Please see this file for
# documentation and usage

#
# Set up the environment if not already done
#
#if [ "x$STADENROOT_1_6" = "x" ]
#then
#    STADENROOT=`which gap4 | sed -e 's#[^/]*/[^/]*$##'`	
#    export STADENROOT
#    . $STADENROOT/staden.profile
#fi

#
# Run it!
#
exec view_alignment.pl ${@+"$@"}
