#!/usr/local/bin/perl 

use strict;
use Bio::AlignIO;
use Bio::EnsEMBL::DBSQL::DBAdaptor;
use Bio::EnsEMBL::ExternalData::Family::FamilyAdaptor;

# These could go in SiteDefs
my $jalview_archive  = "http://www.sanger.ac.uk/Users/michele/jalview.jar";
my $jalview_class    = "jalview.ButtonAlignApplet";


my $family = $ARGV[0];#$q->param('family');

if (defined($family)) { 
    process_Family($family);
}


############################################################################
sub process_Family {

    my ($family_id) = @_;

    my $family;
    my $alignstr;
    my $align;
    my $db;
    my $dbobj = new Bio::EnsEMBL::DBSQL::DBAdaptor(-dbname=>'family102',
						   -host=>'ensrv1',
						   -user=>'ensadmin',
						   );

    my $db = Bio::EnsEMBL::ExternalData::Family::FamilyAdaptor->new($dbobj);

    $family = $db->get_Family_by_id($family_id); 
    $align  = $db->get_Alignment($family);

    my @genes     = $family->each_ens_gene_member;
    my @swissprot = $family->each_member_of_db('SPTR');


    make_jalview_html($align,$jalview_archive,$jalview_class);

}
    
sub make_jalview_html {
  my ($align,$archive,$class) = @_;

  my $numseqs  = scalar($align->eachSeq);
  my $fontsize = 10;

  print<<EOH;
        <table align="center" width="40%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
    	<td colspan="3" class="black"><img src="/gfx/blank.gif" width="1" height="1"></td> 
        </tr>
        <tr valign="center" class="yellow2">
          <th><img src="/gfx/blank.gif" width="15" height="22"></th>
          <th align="left" class="arial">Jalview Java Alignment Viewer/Editor</th>
          <th><img src="/gfx/blank.gif" width="15" height="22"></th>
        </tr>

    	<TR class="yellow1">
    	<td><img src="/gfx/blank.gif" width="15" height="22"></td>
        <TD align="left">

	  Press the button below to load up the alignment into jalview.  <br>
EOH
 
  print "<center><APPLET archive=$archive\n";
  print "code=$class\n";
  print "width  = 200\n";
  print "height = 35>\n";

  print  "<PARAM name=\"numseqs\"  value=$numseqs>\n";
  print  "<PARAM name=\"fontsize\" value=$fontsize>\n";
  print  "<PARAM name=\"background\" value=\"255,255,231\">\n";

  my $i = 1;

  foreach my $seq ($align->eachSeq) {
    print("<PARAM name=\"seq$i\" value=\"" . $seq->seq . "\">");
    print("<PARAM name=\"id$i\"  value=\"" . $seq->id  . "\">");
    $i++;
  }
  print ("</APPLET></td>\n");

  	print<<EOS;
     	   <td><img src="/gfx/blank.gif" width="15" height="22"></td>
    	</TR>
    	<tr>
    	    <td colspan="3" class="grey1"><img src="/gfx/blank.gif" width="1" height="1"></td>
    	</tr>
        </table><br><br>
EOS

}


sub print_alignment  {
  my ($align) = @_;

  my $maxid  = 0;
  my $maxlen = 0;
  my $width  = 60;
  
  foreach my $seq ($align->eachSeq) {
    if (length($seq->id) > $maxid) {
      $maxid = length($seq->id);
    }
    if ($seq->length > $maxlen) {
      $maxlen = $seq->length;
    }
  }
  $maxid += 2;
  
  my $start = 1;
  

  print<<EOH;

        <table align="center" width="40%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
    	<td colspan="3" class="black"><img src="/gfx/blank.gif" width="1" height="1"></td> 
        </tr>
        <tr valign="center" class="yellow2">
          <th><img src="/gfx/blank.gif" width="15" height="22"></th>
          <th align="left" class="arial">Family Alignment</th>
          <th><img src="/gfx/blank.gif" width="15" height="22"></th>
        </tr>

    	<TR class="yellow1">
    	<td><img src="/gfx/blank.gif" width="15" height="22"></td>
        <TD align="left"><pre>
EOH

  while ($start < $maxlen) {
    print_alignment_chunk($align,$start,$width,$maxid);
    $start += $width;
  }

        print "</pre></td>\n";

  	print<<EOS;
     	   <td><img src="/gfx/blank.gif" width="15" height="22"></td>
    	</TR>
    	<tr>
    	    <td colspan="3" class="grey1"><img src="/gfx/blank.gif" width="1" height="1"></td>
    	</tr>
        </table><br><br>
EOS
}

sub print_alignment_chunk {
  my ($align,$start,$width,$maxid) = @_;
  my $end = $start + $width-1;
  
  
  foreach my $seq ($align->eachSeq) {
    if ($end > $seq->length) {
      $end = $seq->length;
    }
    
    my $id       = $seq->id;
    my $url = "/perl/textview?num=%s>%{$maxid}s</a>";
    printf "$url %s\n",$id,$id,$seq->subseq($start,$end);
  }
  print("\n");
}
