
<table class="spreadsheet" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
</tr>


<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/"><i>Anopheles gambiae</i></a> (mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mosquito/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/"><i>Apis mellifera</i></a> (honey bee)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_bee/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/"><i>Bos taurus</i></a> (cow)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_cow/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/"><i>Caenorhabditis elegans</i></a> (nematode)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_celegans/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/"><i>Canis familiaris</i></a> (dog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_dog/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/"><i>Ciona intestinalis</i></a> (transparent sea squirt)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_ciona/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/"><i>Danio rerio</i></a> (zebrafish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_zebrafish/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/"><i>Drosophila melanogaster</i></a> (fruit fly)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fly/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/"><i>Fugu rubripes</i></a> (torafugu)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fugu/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/"><i>Gallus gallus</i></a> (chicken)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chicken/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/"><i>Homo sapiens</i></a> (human)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_human/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/"><i>Mus musculus</i></a> (house mouse)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mouse/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/"><i>Pan troglodytes</i></a> (chimpanzee)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_chimp/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/"><i>Rattus norvegicus</i></a> (Norway rat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_rat/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/"><i>Saccharomyces cerevisiae</i></a> (baker's yeast)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_scerevisiae/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/"><i>Tetraodon nigroviridis</i></a> (spotted green pufferfish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_tetraodon/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/"><i>Xenopus tropicalis</i></a> (western clawed frog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_xtropicalis/data/mysql/">FTP</a></td>
</tr>
	    </table>