
<table class="spreadsheet" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
</tr>


<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/"><i>Anopheles gambiae</i></a> (HASH(0x812c180))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/"><i>Apis mellifera</i></a> (HASH(0x813a054))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/"><i>Bos taurus</i></a> (HASH(0x8139fe8))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/"><i>Caenorhabditis elegans</i></a> (HASH(0x813a024))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/"><i>Canis familiaris</i></a> (HASH(0x872a334))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/"><i>Ciona intestinalis</i></a> (HASH(0x8139f70))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/"><i>Danio rerio</i></a> (HASH(0x813a06c))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/"><i>Drosophila melanogaster</i></a> (HASH(0x812c180))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/"><i>Fugu rubripes</i></a> (HASH(0x813a054))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/"><i>Gallus gallus</i></a> (HASH(0x8139fe8))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/"><i>Homo sapiens</i></a> (HASH(0x813a024))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139f70)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/"><i>Mus musculus</i></a> (HASH(0x872a334))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a06c)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/"><i>Pan troglodytes</i></a> (HASH(0x8139f70))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x812c180)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/"><i>Rattus norvegicus</i></a> (HASH(0x813a06c))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a054)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/"><i>Saccharomyces cerevisiae</i></a> (HASH(0x812c180))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x8139fe8)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/"><i>Tetraodon nigroviridis</i></a> (HASH(0x813a054))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x813a024)/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/"><i>Xenopus tropicalis</i></a> (HASH(0x8139fe8))</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_HASH(0x872a334)/data/mysql/">FTP</a></td>
</tr>
	    </table>