<h4>7 eutherian mammals Pecan</h4>
Pan troglodytes<br />
Mus musculus<br />
Homo sapiens<br />
Canis familiaris<br />
Rattus norvegicus<br />
Bos taurus<br />
Macaca mulatta<br />
<h4>10 amniota vertebrates Pecan</h4>
Mus musculus<br />
Canis familiaris<br />
Rattus norvegicus<br />
Homo sapiens<br />
Pan troglodytes<br />
Gallus gallus<br />
Monodelphis domestica<br />
Bos taurus<br />
Ornithorhynchus anatinus<br />
Macaca mulatta<br />
